### ISSUE TITLE
[SF3] Server Pack Not Launching - ClassNotFoundException

### ISSUE THREAD

**Issue by everseeking** [TechReborn/RebornStorage#1]
#### Setup
* Sky Factory 3 (Server Zip) - `FTBPresentsSkyfactory3Server_3.0.3`
Includes:
   * `RebornCore-1.10.2-2.12.1.96-universal.jar`
   * `RebornStorage-1.10.2-1.0.0.15.jar`
   * `refinedstorage-1.2.16.jar`

#### Issue
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RebornStorage (rebornstorage)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: required-after:forge;required-after:reborncore;after:refinedstorage`
* [Report](https://gist.github.com/everseeking/2ce8ecfc62e971a91a6ae23ecd4eface)

#### Notes
* Seems to not like [this](https://github.com/TechReborn/RebornStorage/blob/cf263c13cce5a467084aa181ac11018e558d1a74/src/main/java/RebornStorage/lib/ModInfo.java#L12) - is formatting wrong?
* Removed Foamfix, [same result](https://gist.github.com/everseeking/4de0ae36dadfb8c770afd2a3743589e9)

**Comment by gigabit101** [comment]
just fixed new build going up now

**Comment by everseeking** [comment]
Cool, thanks for the fix. 

But my eyes just caught something looking at your [commit](https://github.com/TechReborn/RebornStorage/commit/f1c5f06d57303f98abb35cc737fb09b4e0ba58b2) - "String MOD_DEPENDENCUIES" is that mispelling (extra "U") of dependencies going to be an issue?

**Comment by way2muchnoise** [comment]
The spelling of a field name doesn't really matter

**Comment by everseeking** [comment]
Ok, just wondering if that was a local thing to the mod or if Forge uses that field and needs the correct spelling. Totally just giving a semi-educated guess when I noticed it, never built a Forge mod myself so won't try to sound like I have.

**Comment by way2muchnoise** [comment]
@everseeking This is where the real magic happens https://github.com/TechReborn/RebornStorage/blob/master/src/main/java/RebornStorage/RebornStorage.java#L20
