### ISSUE TITLE
Doesn't Actually Craft

### ISSUE THREAD

**Issue by Joshwoo70** [TechReborn/RebornStorage#10]
Requested 3 Magma Cream... pattern is already in the multiblock
![2017-01-18_21 01 26](https://cloud.githubusercontent.com/assets/7894419/22065072/69ef476e-ddc1-11e6-9e3d-f8eb1bd02e36.png)
Configuration (3x3) :
![2017-01-18_21 01 34](https://cloud.githubusercontent.com/assets/7894419/22065091/80e7953e-ddc1-11e6-91b7-7b5abbc8e71e.png)

**Comment by way2muchnoise** [comment]
Pretty sure you made a processing pattern by accident. Crafting patterns are made in the pattern grid, as opposed to processing patterns in the encoder.

**Comment by modmuss50** [comment]
So is this not our issue?

**Comment by BrisingrAerowing** [comment]
I am having the same issue, and I created the pattern with a Pattern Grid.

This is with crafting a block of coal.

**Comment by gigabit101** [comment]
I will take a look at this tonight I can't say that I have had this issue and I have been playing with the mod in my ssp world now for over 2 weeks

**Comment by BrisingrAerowing** [comment]
I'll try with just this mod and RefinedStorage to see if there is some kind of conflict.

**Comment by BrisingrAerowing** [comment]
OK, it works with just this mod and its dependencies. So this is a mod conflict.

@Joshwoo70 What is your modlist? If we can get the intersection of our mods, we can narrow this down to a smaller subset of mods.

**Comment by BrisingrAerowing** [comment]
Playing around with this more lead me to discover that a 4 x 4 x 4 crafter design works (4 CPUs and 4 Storage Blocks). I will try a larger design, like the 7 x 7 x 7 one I used before (it had 66 pages!)

**Comment by BrisingrAerowing** [comment]
And now I can't replicate this. I did update some of my mods after finding this, and one of them may have been the culprit and already fixed the issue.

@gigabit101  Could this be reclosed?

**Comment by modmuss50** [comment]
If someone else has the issue I think it should be kept open

**Comment by Joshwoo70** [comment]
@BrisingrAerowing will keep in check later... also o/ from TFB :P
