### ISSUE TITLE
Suggestion: Ability to name the pages

### ISSUE THREAD

**Issue by Knito58** [TechReborn/RebornStorage#100]
I tend to have pages for vanilla, refined storage, xtra utils and so forth.

... and in Refined Storage Crafters the output item is rendered instead of the pattern glyph. Would you consider to show the output, too?

Thanks for the good work.

**Comment by modmuss50** [comment]
Page names are a good idea!

and by the second part I assume you mean it renders the actual item (Same as holding shift)

**Comment by Knito58** [comment]
Thank you for thinking positively about part 1 of the suggestion. Yes, the second part is still like it has been long time before the same in Refined Storage. But now things have changed in Refined Storage: You do not need to hold down the shift key anymore. The crafters show the recipes "toute de suite". Albeit there's much more code when first a key must be held down for the user it is easier to just watch. Yes, it hurts to cut away good code for no other reason but compatibility. This would even out the look and feel with RS and RS.
:>

**Comment by modmuss50** [comment]
For 2, I spoke to the RS dev and he has added in an API I can use to provide the exact same functionality. 

Sounds like I have some coding to do :)

**Comment by Knito58** [comment]
Yay! I'm very happy to hear this. 👍
