### ISSUE TITLE
How in GODS good graces does the io port work?

### ISSUE THREAD

**Issue by OmegaDarkMatter** [TechReborn/RebornStorage#102]
It would be great if there was a manual ingame

**Comment by drcrazy** [comment]
What IO port?

**Comment by modmuss50** [comment]
It should allow you to import in and out patterns with pipes. It does not provide the entire inventory.

**Comment by OmegaDarkMatter** [comment]
ooooo ok. I was REALLY hopping it would allow me to connect the enderio conduits to it and make them act like the Refined storage cables. hint hint wink wink nudge nudge

**Comment by modmuss50** [comment]
Doesn’t enderio have refined storage cables? If not that would be a suggestion you should pass onto the ender io team.
