### ISSUE TITLE
Picking up Reborn Storage Disks corrupts player data

### ISSUE THREAD

**Issue by Moobien** [TechReborn/RebornStorage#103]
This is on a server but I don't have log access, but twice now (256k disk and 1024k disk) when I have collected the disk from my RS system I instantly get disconnected from the server and my player data is getting corrupted.

RS Version: refinedstorage-1.6 (version that still has solderers)
Reborn Storage Version: RebornStorage-3.1.0.56
Reborn Core: RebornCore-3.8.9.300
MC 1.12.2

**Comment by EpicSquid** [comment]
Chiming in on this. Here is the relevant log from the server file. https://pastebin.com/pRm7BQc3

**Comment by raoulvdberge** [comment]
Aah, `StorageDiskType` has been renamed to `StorageType`. Just a simple API mismatch.

**Comment by modmuss50** [comment]
Updated version can be found here, https://jenkins.modmuss50.me/job/Team%20Reborn/job/RebornStorage/job/1.12/

**Comment by Moobien** [comment]
Thanks @modmuss50
