### ISSUE TITLE
[1.12.2] RebornStorage version 3.1.0.58 not converting old patterns when upgrading from version 3.0.6.43

### ISSUE THREAD

**Issue by escman1999** [TechReborn/RebornStorage#104]
there's supposed to be conversion code; but it seems that things aren't working as intended; upon loading a world that previously used rebornstorage version 3.0.6.43, all old patterns that were in the rebornstorage multiblock are invalid
![2018-07-05_19 56 34](https://user-images.githubusercontent.com/6901624/42379383-7703653a-80f8-11e8-87ce-f63724f1b684.png)

**Comment by escman1999** [comment]
the patterns that aren't invalid, are ones i just created

**Comment by raoulvdberge** [comment]
I still have to make that conversion code available in the API.

**Comment by escman1999** [comment]
i know; but one of the rebornstorage devs told me to open an issue; so i did

**Comment by raoulvdberge** [comment]
Fixed by https://github.com/raoulvdberge/refinedstorage/commit/7fc99b55476ee05c0b87d96b686b49ad81278113

Call `IOneSixMigrationHelper#migratePatternInventory` when reading the crafting node from NBT.

If it returns true, you have to mark the inventory as dirty.

**Comment by modmuss50** [comment]
Sounds good, I’ll get around to adding when I get a chance.

**Comment by modmuss50** [comment]
ok, should be fixed now, let me know of any more issues
