### ISSUE TITLE
Forge 14.23.4.2729 fails crafting in multiblock structure

### ISSUE THREAD

**Issue by Knito58** [TechReborn/RebornStorage#105]
I updated Forge today to the latest version. All recipes in the multiblock just don't work anymore. The crafting monitor shows activity, but in fact nothing gets done. Recipes in crafters work.

Forge 14.23.4.2729, RS 3.1.0.50

**Comment by modmuss50** [comment]
Do patterns work in the normal crafter from refined storage?

**Comment by Knito58** [comment]
Yes they do.

**Comment by Knito58** [comment]
Sorry, false positive. SOME crafter recipes work, but not all. There's something broken. The machines do produce the components for the basic processor in the furnace and the solderers but the assembly fails.
Seems as if RS does not recognize that the imported items can now be used. And the count goes not up although the item should be there. So new answer: NO they don't.
After 15 minutes the system still chews on 10 basic processors.

**Comment by Knito58** [comment]
There's a newer Refined Storage Version on [Jenkins ](https://jenkins.raoulvdberge.com/job/refinedstorage/)(1.6) but it causes Reborn Storage to crash in the Loader.

**Comment by Knito58** [comment]
Went back to Forge 14.23.3.2698 and it does not help anymore. The system still is broken. Cannot produce basic processors which only need furnace and solderers. The furnace happily burns my quartz but on import the silicon is negated. My quartz stock is drained for nothing as well es my iron ingots which just get "printed" and send to NIL. Trying to load a backup which worked.
Edit: RS & RS are back again working thanks to a backup.

**Comment by modmuss50** [comment]
working fine in latest version
