### ISSUE TITLE
Possible bug with displaying items in multi-block crafter.

### ISSUE THREAD

**Issue by Ditiae** [TechReborn/RebornStorage#109]
I'm having a weird texture issue where some items sharing item textures of items that have very different textures. The textures that are being shared are between similar items, though different and with different textures. I've mainly seen this issue with draconic evolution and unsure if the issue is entirely RebornStorage's or if its an issue elsewhere. I do know for some of these they are using subitems, however so do refined storage for their storage disks which work just fine. At first, textures were completely invisible but I figured it was just textures glitching so I disabled my texture pack and things that were once invisible turned into this issue. I have tried reloading textures a few times, however, to no avail. Sorry for the paragraph and sorry if this issue is not particularly yours. An example image of what I see with draconic evolutions items are shown below:

![image](https://user-images.githubusercontent.com/30428646/43066270-d3a24430-8e29-11e8-93a9-31868a2872ee.png)

A few of the items shown have actual textures looking as such: 

![image](https://user-images.githubusercontent.com/30428646/43066344-03a63970-8e2a-11e8-9bcb-36d278899375.png)

Thanks.

**Comment by modmuss50** [comment]
Can you test in just a refined storage crafter and see if you have the same issue

**Comment by Ditiae** [comment]
Yes.
![image](https://user-images.githubusercontent.com/30428646/47526985-08764580-d867-11e8-96af-970db125747b.png)

Same within the inventory.
![image](https://user-images.githubusercontent.com/30428646/47526998-14fa9e00-d867-11e8-8d00-8adbc5721f85.png)

**Comment by modmuss50** [comment]
That’s an issue with refined storage then, not something I can fix.

**Comment by Ditiae** [comment]
Yeah was just gonna edit my comment and mention that, sorry. Havn't played this pack for months. Just thought I'd hop back on and try and help figure it out. But, yes, would appear its not your issue. Thanks for looking into it.
