### ISSUE TITLE
Autocrafting speed issues

### ISSUE THREAD

**Issue by Dissgruntled** [TechReborn/RebornStorage#111]
RebornStorage-1.12.2-3.2.1.63
RebornCore-1.12.2-3.9.2.319-universal
Refined Storage 1.6.2
Forge 1.12.2 - 14.23.4.2745

Using the latest versions of Reborn Storage and Refined Storage, the multiblock crafter seems extremely slow compared to the RS crafters. I have 28 crafting CPU's in the structure and the speed is the same as it is with only 1. Adding crafting CPU's does not increase crafting speed at all.

**Comment by JBSTheGamer** [comment]
i know your pain the newest update of reborn storage broke the crafting unit speed

**Comment by JBSTheGamer** [comment]
now its really slow

**Comment by modmuss50** [comment]
ok, ill take a look when I get a chance. Seems something may have changed.

**Comment by modmuss50** [comment]
Humm, in my testing I am sending the correct amount of speed upgrades to Refined Storages API, it prob doesn't like having more than 4 speed upgrades. (26 in my testing) before in older versions of RS this seemed to work fine and the crafting would be very quick.

@raoulvdberge do you have any input on this?

Thanks in advance 👍

**Comment by raoulvdberge** [comment]
Oh:

```java
    private int getTickInterval(int speedUpgrades) {
        switch (speedUpgrades) {
            case 1:
                return 8;
            case 2:
                return 6;
            case 3:
                return 4;
            case 4:
                return 2;
            case 0:
            default:
                return 10;
        }
    }
```

Will change it to this:

```java
    private int getTickInterval(int speedUpgrades) {
        switch (speedUpgrades) {
            case 1:
                return 8;
            case 2:
                return 6;
            case 3:
                return 4;
            case 4:
                return 2;
            case 0:
                return 10;
            default:
                return 2;
        }
    }
```

**Comment by raoulvdberge** [comment]
Fixed in

https://github.com/raoulvdberge/refinedstorage/commit/4a9aa52280047fd92c60b746c9f574e6a6d62593

**Comment by JBSTheGamer** [comment]
yes finally the pain is over and also the wireless fluid grid was also crashing me and its now fixed and

**Comment by JBSTheGamer** [comment]
when will the fix be released on the page just asking

**Comment by raoulvdberge** [comment]
It has just been released

**Comment by JBSTheGamer** [comment]
i do not see the fix jar in the files tab of reborn storage or is it the dev jar file

**Comment by JBSTheGamer** [comment]
oh its on the jenkins website

**Comment by modmuss50** [comment]
It was fixed in refined storage
