### ISSUE TITLE
IO Port

### ISSUE THREAD

**Issue by Trellinane** [TechReborn/RebornStorage#113]
Hello,

Sorry for posting in issues, but I could not find anything on the use of the IO Port block on any websites or forums.  What is the purpose of the IO Port?  Is it for Open Computers/Computercraft interfacing?  Please let me know. Thank you.

**Comment by modmuss50** [comment]
Hi,

The IO port is used to pipe patters in and out of the multiblock controller,

We dont have any support for computer mods currently. If that is wanted it could be looked into.
