### ISSUE TITLE
Freeze/Crash when putting a storage drive from reborn storage in a strongbox from thermal expansion

### ISSUE THREAD

**Issue by Darthip** [TechReborn/RebornStorage#115]
> Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes

![capture](https://user-images.githubusercontent.com/42181820/44242043-ece82200-a1c7-11e8-9c17-caf82e2b8a57.PNG)

When putting a 1024k (with 100k items) storage drive from reborn storage in a strongbox

The crash is 100% reproducible

[i posted it on the issue tracker of cofh](https://github.com/CoFH/Feedback/issues/1261)

I'm on the up-to-date allthemods3 pack so:

RefinedStorage 1.5.34
RefinedStorageAddons 0.3
RebornCore 1.12.2-3.9.2.319
RebornStorage 1.12.2-3.1.0.50

and
ThermalExpansion 1.12.2-5.5.0.29

I said on reddit that:
putting the disk by hand in the strongbox-> freeze
by EnderIo item conduit and retrieving it by item conduit-> ok
opening the strongbox with the drive in it-> freeze
picking the box with the drive in it with the crescent hammer (plus watching its tooltip) -> ok
placing the box with the drive in it -> freeze

puting the disk in a chest/ender chest -> ok
picking the chest with a holding bag from cylic -> ok

**Comment by modmuss50** [comment]
Update your mods. This has been fixed in RS 1.6
