### ISSUE TITLE
Horrible duplication glitch with Mystical Agriculture.

### ISSUE THREAD

**Issue by warplord** [TechReborn/RebornStorage#120]
I used Reborn Storage autocrafting multiblock to craft 64 of the tier 5 mystical agriculture essence (which requires thousands of lvl 1 essences), it crafted fine but after the crafting process I ended up with nearly 100 000 more lvl 1 essence than before I started. 
Something somewhere got duplicated very severely.

**Comment by modmuss50** [comment]
Can you test the patterns in a standard refined storage crafting block?

**Comment by warplord** [comment]
I will give it a try.

**Comment by modmuss50** [comment]
No response, people have had similar isssues when trying with just refined storage. Please open an issue with them.
