### ISSUE TITLE
Reborn Storage Assembler wreaks hell on staged recipes that return multiple items

### ISSUE THREAD

**Issue by Peliex** [TechReborn/RebornStorage#121]
Having a problem in which Mystical Agriculture essence recipes, which require an infusion crystal to manufacture, do not recognize properly that only one crystal is necessary to complete the operation
![image](https://user-images.githubusercontent.com/20830349/46601594-63a3ec00-caa2-11e8-8045-360a35be7d1d.png)
![image](https://user-images.githubusercontent.com/20830349/46601603-70c0db00-caa2-11e8-8f48-b2580cfa0f13.png)
As to whether this is an intrinsic problem in the system itself or if it's something that the assembler can't handle I'm not sure

**Comment by modmuss50** [comment]
can you try by having the patterns in just refined storage crafters?

**Comment by Peliex** [comment]
> can you try by having the patterns in just refined storage crafters?

I'll give that a shot and see how it does

**Comment by modmuss50** [comment]
No response, my guess is it’s an issue with refined storage it’s self
