### ISSUE TITLE
duplication bug with wireless crafter reborn storage V 3.2.2.65

### ISSUE THREAD

**Issue by vizzair** [TechReborn/RebornStorage#123]
simply put items in the crafting grid in the wireless crafter, then hit the "clear" button to put them back into storage, the items are duplicated.
Doesn't do it with the wired refined storage crafting grid.

**Comment by gigabit101** [comment]
But we don't add a wireless crafter?

**Comment by vizzair** [comment]
sorry - long day, its refined storage addons ...
Now to find them to report it !
