### ISSUE TITLE
possible dupe with the Reborn Storage crafter

### ISSUE THREAD

**Issue by ghost** [TechReborn/RebornStorage#124]
- Refined Storage Version 1.6.5
- Refined Storage Addons Version 0.4.2
- Reborn Storage Version 3.2.2.65
- Reborn Core version 3.10.2.337

So there is the dupe glitch I was crafting 10k redstone block and at the start I had like 700k Redstone dust
After I started the recipe it gave me 32Million redstone dust and the 10k blocks 
This dupe glitch was done on StoneBlock 1.0.19 with a simple storage network like this https://gyazo.com/2a8cd883580a20c8ace6cc7f550eaaa3
It was on a server

**Comment by modmuss50** [comment]
Can you try without using reborn storage blocks? Put all the patters into standard refined storage crafters and see if it still happens.

If not please create a creative mode world with just RebornStorage and Refined storage and see if you can reproduce the issue. There isnt enough information for me to even start to look at this issue.

I just pass the patters to Refined Storage using their api so I dont see how it can be an issue with Reborn Storage, but I am happy to be corrected.

Thanks

**Comment by ghost** [comment]
Testing it right now

**Comment by ghost** [comment]
It does it with the Refined Storage Crafter

**Comment by modmuss50** [comment]
Ok, I would open an issue on the refined storage issue tracker along with intrusions on how to cause it. Thanks for the initial issue.

**Comment by ghost** [comment]
Wait There I think its the Quantum Storage unit from Quantum Storage the problem

**Comment by TheForceteam** [comment]
Wait There I think its the Quantum Storage unit from Quantum Storage the problem

**Comment by modmuss50** [comment]
Ok, i would recommend opening an issue on the quantum storage issue tracker.
