### ISSUE TITLE
Renaming the Multiblock

### ISSUE THREAD

**Issue by presdec** [TechReborn/RebornStorage#125]
Once anyone's crafted a multiblock it makes sence that it will become their primary method of autocrafting. 

However neither in the Crafter Manager nor in the structure itself can I find a method to rename it so that the Multiblock storage appears on the top of the list.

This would merely be convinient in order to have it appear first so that patterns can be shift clicked into it.

**Comment by modmuss50** [comment]
I dont believe this is possible to fix, sorry.
