### ISSUE TITLE
potential world corruption when using Reborn Multistructure

### ISSUE THREAD

**Issue by LiquidLighter** [TechReborn/RebornStorage#127]
I have around 800+ hours on a world in foolcraft3 version 1.5.4
I found that i can use a auto crafting multi structure instead of like 100 craters from refined storage.
So i immediately built the max size for the multi structure of 16x16 and i was able to put all my patterns in. 
After a few minutes my game crashed and i can no longer load into the world. 
I made a new world and attempted to recreate the problem, as soon as i placed down any of the multi structure blocks (i.e frame) i get an error from Refined Avaritia. 

report link i was given https://paste.dimdev.org/cequlolegu.mccrash

**Comment by raoulvdberge** [comment]
Go report this to refined avaritia

**Comment by modmuss50** [comment]
Nothing to do with us, sorry.
