### ISSUE TITLE
Slow autocrafting speed

### ISSUE THREAD

**Issue by DrWhovahkiin** [TechReborn/RebornStorage#128]
Noticed this on Stoneblock mod pack version 1.0.25
Reborn core 3.10.2.237
RebornStorage 3.2.2.65
Refined Storage 1.6.8

Not sure if this is still an issue, will update with tests on newer versions..

Anyway, Adding more than 4 Crafting CPUs has no effect on the speed of the crafting.
Tested with a 4x4x4 machine with 4 crafting CPUs = same speed as 16x16x16 with 2,743 Crafting CPUs.

**Comment by DrWhovahkiin** [comment]
Confirmed still an issue in StoneBlock 1.0.27
reborn core 3.10.4.348
refined storage 1.6.9
others are the same.

**Comment by modmuss50** [comment]
Nothing I can do to fix it sadly. It’s a limitation of refined storage, I pass the number of cpus to refined storage correctally but it doesn’t handle any more than 4.

**Comment by DrWhovahkiin** [comment]
:(
Not gonna lie... makes this mod pretty useless.

**Comment by DrWhovahkiin** [comment]
Maybe instead of passing it to refined storage, it could act as it’s own crafter? 
Making it faster.
