### ISSUE TITLE
Multiblock Storage Crafter isn't recognizing the storage blocks.

### ISSUE THREAD

**Issue by idozer32** [TechReborn/RebornStorage#13]
I got 82 storage blocks but the block still isn't recognizing them, this broke my game as I had a ton of patterns in it,tried rebuilding it but didn't work aswell.

**Comment by way2muchnoise** [comment]
Could you post a screenshot of what you are trying?

**Comment by idozer32** [comment]
![2017-01-22_17 14 17](https://cloud.githubusercontent.com/assets/25284354/22185115/a05732a0-e0c6-11e6-920f-209803d4244e.png)
![2017-01-22_17 14 20](https://cloud.githubusercontent.com/assets/25284354/22185116/a05985f0-e0c6-11e6-82b2-c0762cd2e259.png)
![2017-01-22_17 14 26](https://cloud.githubusercontent.com/assets/25284354/22185117/a05e5dc8-e0c6-11e6-8f62-640e1d2e8de6.png)
![2017-01-22_17 14 35](https://cloud.githubusercontent.com/assets/25284354/22185119/a0633b18-e0c6-11e6-9d16-310d374a12f1.png)
![2017-01-22_17 14 41](https://cloud.githubusercontent.com/assets/25284354/22185118/a062fe82-e0c6-11e6-8480-decec5397f50.png)
![2017-01-22_17 14 43](https://cloud.githubusercontent.com/assets/25284354/22185120/a0657df6-e0c6-11e6-9f7a-1febd0d6acad.png)
![2017-01-22_17 16 26](https://cloud.githubusercontent.com/assets/25284354/22185121/a072f508-e0c6-11e6-93a0-e8cb755c00c9.png)
I had it in the inside of it in a chess pattern before, it's like that now because I thought it would be fixed like that but nope, everytime I open the GUI of the crafter it "empty"(or "substitutes" my whole inventory with the patterns but I already broke the sotrage blocks to get the patterns back) my inventory and I have to open any kind of storage to fix it, in this case I drop my wireless grid and pick it up to open the refined storage grid.

**Comment by modmuss50** [comment]
@way2muchnoise Darko told me the last update broke it. I can take a look tomorrow if you like.
