### ISSUE TITLE
Sort Inventory while in UI crashes game/closes ingame server

### ISSUE THREAD

**Issue by xephosarkeyus** [TechReborn/RebornStorage#130]
I was playing the Stoneblock modpack, and for no reason, I thought hitting the Sort inventory key (I believe from InventorySorter) would work and help sort the patterns.

Turns out, it was a bad idea. It took me 4 tries to actually join my world again. Is this the mod's issue or is the blame on InventorySorter?

**Comment by modmuss50** [comment]
can you please post a crash log (create a new creative world if you need to)
