### ISSUE TITLE
Disappearing Patterns

### ISSUE THREAD

**Issue by MrRunnyBum** [TechReborn/RebornStorage#131]
Hi, I'm currently using Reborn Storage on my server. Every time i close the server down then reopen it i find that one of the pattern pages inside the multiblock structure is completely blank when they should all be full and all of my monitors and grids have been turned around plus any covers on cables have been removed. The is causing a fairly annoying problem with progression. The core jar version is 3.10.4.348 and the other jar version is 3.2.2.65.
https://pastebin.com/JswqLdhc link to crashlog

**Comment by MrRunnyBum** [comment]
Nevermind, found a fix. All i needed to do was go into a backup and copy the refinedstorage_disks.dat and _nodes.dat files from world/data then put them in the current world. everything is back.

**Comment by modmuss50** [comment]
not my bug, sorry
