### ISSUE TITLE
Server hang then force crash

### ISSUE THREAD

**Issue by VallenFrostweaver** [TechReborn/RebornStorage#132]
Turns out this issue was assumed to be Refined Storage when it's actually Reborn Storage. Info here: https://github.com/raoulvdberge/refinedstorage/issues/2080

**Comment by modmuss50** [comment]
I think this may be a case of just too many patterns? can you reproduce it easily?

**Comment by VallenFrostweaver** [comment]
Not reliably that we've tried. They aren't too keen on trying to crash the server and losing progress so I cant speak to a lot of testing. One had a pattern set up of maybe a 6x6 cube while the other made a max size 64x64.

**Comment by modmuss50** [comment]
humm, 64x64 possibly, adding a config to limit the size might not be a bad idea.

6x6 size.. thats a more reasonable size I will have to do some testing, but some times it can be down to just a few recipes that take a while to validate that the recipe is valid. (fluid recipes are one example of that this that I have seen)

I dont really have a good solution to this issue appart from using less patterns. I dont believe that I update the patters more than necessary, but it may be worth me checking on that.

**Comment by VallenFrostweaver** [comment]
Here's the thing though is that it took a good IRL day before it became unrecoverable. It would crash at maybe 4 hrs then 3, 2 etc. So it got progressively worse. And during this time nithing was being crafted or done. It was just a loaded area.

**Comment by modmuss50** [comment]
ah, thats an interesting thing to note, I may setup a local server and try and create a more real to life test (with other mods installed).

Thanks a lot for your help

**Comment by modmuss50** [comment]
Should be a scale of the number of patters storage blocks better come next update.
