### ISSUE TITLE
Transmuted Storage Drives Do Not Work

### ISSUE THREAD

**Issue by MrC74rk** [TechReborn/RebornStorage#134]
I'm thinking this may be more of a ProjectE Bug, but when I put a 256k Storage Disk in a transmutation table, the transmuted versions do not work. I also notice the tool-tips differ slightly. The original shows 0/256,000 items in use. The copy does not include this data. 

![origional](https://user-images.githubusercontent.com/45373566/49045660-3ec12080-f197-11e8-89ed-04b03da53b64.png)
![copy](https://user-images.githubusercontent.com/45373566/49045662-3ec12080-f197-11e8-9bd3-821e8137a50b.png)

**Comment by modmuss50** [comment]
Does this also happen with the standard refined storage disks?

**Comment by MrC74rk** [comment]
Just checked.....YEP! Sure does. definitely either Refined Storage or ProjectE issue. Thanks for the quick response.
