### ISSUE TITLE
Lag with large multiblocks

### ISSUE THREAD

**Issue by Darkere** [TechReborn/RebornStorage#144]
Copied from RS github:

#### Issue description:
Tps lag when crafting with lots of crafting CPU's
#### What happens:
TPS goes down to 2.

#### Steps to reproduce:
1. Make Reborn Storage Autocrafter. (Mine is Max size 16x16x16 with 1 crafting storage the rest are cpus).
2. Setup pattern for Sextuple compressed cobblestone. 
3. Connect creative drawer with cobble.
4. Request 2 Sextuple compressed Cobblestone (Anything more gets caught by the complexity check for me)

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:2815
- Refined Storage:1.6.14

Does this issue occur on a server? [yes/no]yes

#### Profiling
https://www.dropbox.com/s/xkcbyg9bgcomy0l/RSCraftingWithoutOpeningCraftingMonitor.nps?dl=0
Looking at that this might be on reborn Storage? Not sure if he can fix this with the current API but I will post on his git too.

**Comment by modmuss50** [comment]
Should be fixed, thanks.
