### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by bufu1337** [TechReborn/RebornStorage#145]
[crash-2019-04-22_20.21.09-server.txt](https://github.com/TechReborn/RebornStorage/files/3106997/crash-2019-04-22_20.21.09-server.txt)

Hello, i am playing with about 300 mods and i have a giant world which i am playing over 1 year... 
now i have decided to update all mods, because i wanted the mod MineColonies and it requires newest forge version which lead me to update other mods for a working minecraft... 

so yesterday i downloaded the newest versions of all mods, spend the whole day and after a few tries i had minecraft up and running, loadtime about 30mins... 
i can start a new world but i have put so much work into my old world and i want to continue there, but unfortuneatly i cant load my world... 
it crashes and like i see it has something to do with my rebornstorage multiblock autocrafters... 
for each mod i have all recipes in a corresponding multiblock system, and each with his own rs-controller... unfortuneatly the log doesnt give me any hint about which multiblock has an invalid, currupted recipe which causes the crash... 

PLEASE HELP... without the solution to this problem i am not able to play with updated mod-versions 

Sorry for my gramma-mistakes, my english is not the best ;)

Greetings
bufu

**Comment by modmuss50** [comment]
Your English is fine, this seems to be an issue with a mod in your pack and not Reborn Storage.

Finding out what mod might be a bit of a pain.

The mod is crashing when Refined Storage tests the recipe

**Comment by bufu1337** [comment]
Hmmm ok maybe i should compare all recipes, thats possible with crafttweaker... 

PS.: all mods are single downloaded, no modpack... now i subscribed also to each mod :)

**Comment by bufu1337** [comment]
After checking over 10000 recipes i decided to remove all pattern from the reborn multiblocks and destroy all multiblocks... it was a lot of work but now i can load my world... now i have to get all working patterns back into the new multiblocks... problem solved... thx
