### ISSUE TITLE
[Suggestion] Crash when Refined Storage is not installed

### ISSUE THREAD

**Issue by SuperSandro2000** [TechReborn/RebornStorage#147]
You should probably let Forge display an error that you need to install RefinedStorage like many other mods (eg Vazkii's or COFH's) if it is not installed.

**Comment by Jeusey** [comment]
Isn't that fairly obvious already as it is an addon for refined storage?

**Comment by gigabit101** [comment]
This has been done in the 1.18.2 version (Coming soon)
