### ISSUE TITLE
Reborn Storage Energy Usage Issue

### ISSUE THREAD

**Issue by Darkosto** [TechReborn/RebornStorage#15]
If a Reborn Storage crafter has multiple connection points to your RS system, the amount of power required to run the crafter is multiplied by each connection point (i.e. if a cable is running over the top of your crafter, energy usage is calculated at each block the cable touches the crafter). 

1. Build a very simple RS storage system.
2. Build a Reborn Storage crafter.
3. Connect the crafter to the RS system in multiple points.
4. Observe power usage on the RS controller. 

Reborn Storage: 1.0.0.22
Refined Storage: 1.2.17

**Comment by gigabit101** [comment]
fixed in new build
