### ISSUE TITLE
Multi Step Crafting not working

### ISSUE THREAD

**Issue by ghost** [TechReborn/RebornStorage#150]
So i had a reborn storage multiblock and was trying to automate mekanism factories, but the multi step crafting doesn't work. I have plenty of crafting storage blocks, and plenty of crafting CPUs. I am trying to auto craft a elite enriching factory, but it says i don't have the advanced enriching factory, even though i have the pattern. I also have plenty of resources. Any would would be appreciated.

**Comment by Holmesthrone** [comment]
Happens with other mods too like OpenComputers where the lower tier CPU's aren't recognized as usable patterns nor ressources, pretty annoying..
Thing is i don't know if it has to do with Refined Storage way of using data or Reborn Storage's multiblock.

**Comment by gigabit101** [comment]
RebornStorage use the refined storage auto crafting system, In short, if there is an issue with makings things auto craft this is on Refind Storages not and not ours
