### ISSUE TITLE
drive contents just disappeared 

### ISSUE THREAD

**Issue by tonyvans** [TechReborn/RebornStorage#153]

**Comment by tonyvans** [comment]
Hello, weirdest thing happened, the drives I had made just stopped functioning for some reason.
They are no longer visable in the drive bay

![drive](https://user-images.githubusercontent.com/6739653/63289566-48823b00-c274-11e9-90f0-cdbf99d40410.JPG)

and I can remove them but they show as having no contents nor space remaining, it is almost like the system cannot see them anymore.

![blank](https://user-images.githubusercontent.com/6739653/63289587-559f2a00-c274-11e9-80e5-fb7024531861.JPG)

RebornStorage-1.12.2-3.3.4.85.jar. 

no crash or error, just cannot see drive contents.

**Comment by modmuss50** [comment]
There is nothing I can do about this, as we just use the refined storage API and have no control over this.
