### ISSUE TITLE
Pattern Storage and Carry On mod

### ISSUE THREAD

**Issue by KollinsPlays** [TechReborn/RebornStorage#154]
I moved my Reborn Storage multiblock and after using the Carry On mod to move my Crafting Storage blocks to the new location and rebuilding the structure around them,all the patterns disappeared.

Minecraft 1.12.2
Forge 14.23.5.2838
RebornStorage-1.12.2-3.3.4.85.jar
CarryOn+MC1.12.2+v1.12.2.jar

**Comment by gigabit101** [comment]
The patterns are part of the Multiblock and should not be moved in this manner,
