### ISSUE TITLE
[Question] Versioning Scheme

### ISSUE THREAD

**Issue by ElvenChaos** [TechReborn/RebornStorage#155]
The latest release (at time of writing) is RebornStorage-1.12.2-3.3.4._**1**_, but RebornStorage-1.12.2-3.3.4._**85**_ was the previous iteration. Is this an error in versioning, and ~.1 is the correct up to date build, or is ~.1 somehow a release of an older iteration of the mod?

No changelog was released, so I couldn't even compare that to anything.

**Comment by modmuss50** [comment]
It was a mistake, it’s the same file.

A new branch was created causing a new release.
