### ISSUE TITLE
Crafter too slow

### ISSUE THREAD

**Issue by Dani20000** [TechReborn/RebornStorage#157]
I'm playing the modpack "Awakening - Sky of diamonds" and i tried to compare Reborn Storage crafter speed with a normal crafter with 4 speed upgrades...
The Refined Storage crafter with 4 speed upgrades takes 2,48 seconds to make 128 furnaces
The Reborn Storage crafter with 1 CPU (4x3x3) takes ~90 seconds to make 128 furnaces
The Reborn Storage crafter with 1371 CPUs (16x16x9) takes 64,23 seconds to make 128 furnaces
The Reborn Storage crafter with 2743 CPUs (16x16x16) takes 64,08 seconds to make always 128 furnaces... how this is possible?
I read the issue number #136 but there speaks about similiar speeds between a Refined Storage crafter with 4 upgrades and a 70 CPUs Reborn Storage crafter... this is much more slower...
Minecraft version: 1.12.2
Reborn Storage version: 3.3.4.1
Reborn Core version: 3.18.1.514
Refined Storage version: 1.6.15

**Comment by bloodscon** [comment]
Reborn comes into its own when recursive crafting imagine setting off tier 8 solars from solar flux reborn how many normal crafters would you need plus the speed upgrades

**Comment by gigabit101** [comment]
These values have been adjusted in the 1.18.2 version (Coming soon)
