### ISSUE TITLE
RebornStorage crafter is too slow

### ISSUE THREAD

**Issue by BeaterHouba** [TechReborn/RebornStorage#158]
https://github.com/TechReborn/RebornStorage/issues/111

It looks like this is the same problem - Crafter is too slow (I am using more than 32 crafting CPU and 1 crafting of piston takes about 1s )(MC ver. 1.12.2) 
Addon Core ver. 3.18.1.514
Addon ver. 3.3.4.1

Refined Storage ver. 1.6.15

Fix will be appreciated (i don't know if you still support older ver.)

Thank's for your work.

**Comment by gigabit101** [comment]
This would be limited by Refined Storage and not us.

**Comment by modmuss50** [comment]
Make sure you are using the latest version, as the newer versions can go a lot quicker than that.

**Comment by Darkere** [comment]
There is a config to set the crafting speed for the Multiblock. It might be worth a look if that's been changed in your pack.

**Comment by BeaterHouba** [comment]
thanks i will inform Modpack creator maybe he is using some defaults.
