### ISSUE TITLE
Fluid Tank Texture Enhancement

### ISSUE THREAD

**Issue by xanthian** [TechReborn/RebornStorage#162]
![basic_tank_unit_top](https://user-images.githubusercontent.com/7688001/142482748-11c7d909-382d-416b-9b65-14592280c3e0.png)
![industrial_tank_unit_top](https://user-images.githubusercontent.com/7688001/142482753-b3a9b67e-6d7e-4a35-81da-f478258abbb2.png)
![advanced_tank_unit_top](https://user-images.githubusercontent.com/7688001/142482764-53d89d83-b217-4a0e-858e-5ad2544f4263.png)

I'm no artist, nor could I figure out how to get the top texture to rotate with the sides, but the tank texture is impossible to work out which side is which, a small arrow pointing at the front as shown above would be a welcome addition.
Obviously would need to rotate when using the wrench.

**Comment by gigabit101** [comment]
I feel like this issue is on the wrong repo as this mod does not have any rotatable blocks

**Comment by xanthian** [comment]
ahh balls should have been on TechReborn,
If you could move + reopen :)
