### ISSUE TITLE
Fluid disks already exist

### ISSUE THREAD

**Issue by MelanX** [TechReborn/RebornStorage#164]
All the fluid disks added by Reborn Storage still exist, except the 16384k disk.

Version: 4.0.0

Reborn Storage:
![image](https://user-images.githubusercontent.com/26039509/164272775-cf639b05-c577-4386-8661-6f6749a6be9a.png)

Refined Storage:
![image](https://user-images.githubusercontent.com/26039509/164272798-603ad0a0-e9eb-43e2-95f7-e0e7562d4a8c.png)

**Comment by gigabit101** [comment]
Good chance I mixed up the values in the port, Will be fixed in the next version

**Comment by MelanX** [comment]
Keep in mind to adjust the tags then :)

**Comment by gigabit101** [comment]
Fixed in 4.0.1
