### ISSUE TITLE
Reborn Storage World Corruption Fluid Disks

### ISSUE THREAD

**Issue by manmaed** [TechReborn/RebornStorage#168]
**Info**
Minecraft: 1.18.2
Forge: 40.1.16
Refind Storage: 1.10.2
Reborn Storage: 4.0.0

**Description**
Game Crashes When fluild is impoted into a Reborn Storage Disk and makes world unplayable

**Crash Report**
https://pste.me/v1/paste/SV45IfYmTGs/raw

**Steps to reproduce**

1. get system with item disks and reborn storage fluid disks
2. put importer on a tank
3. change impotert to mode fluid
4. Boom CRASH!

**Comment by gigabit101** [comment]
Fixed in 4.0.1

**Comment by manmaed** [comment]
This still seems to be an issue reporting it to Refined Storage as Gaz thinks it might be them causeing the issues
https://github.com/refinedmods/refinedstorage/issues/3300
https://pste.me/v1/paste/QlkfwHsd7yk/raw
