### ISSUE TITLE
Inventory duplicates on the last few Pages of MultiBlock Crafter

### ISSUE THREAD

**Issue by DMNerd** [TechReborn/RebornStorage#169]
The inventory shows up when you scroll far into the MultiBlock Crafter Inventory

Picture:
![2022-05-15_13 47 52](https://user-images.githubusercontent.com/7889445/168471293-0565ca25-99fe-4076-98af-14796d720491.png)
 
Tor reproduce:
Build a big Multiblock Crafter (the one I tested was 8x8x6), two layers of crafter storage
Scroll to the last pages of the inventory

**Comment by DMNerd** [comment]
This issue seems to affect newly formed Crafters only. After full client and world reload, the crafter now shows the correct number of pages and the last pages (84) are not there anymore.

Curiously, when Heat Conductor or Crafting Frame is broken, the multiblock still works and the GUI opens

**Comment by gigabit101** [comment]
Fixed in 4.0.10
