### ISSUE TITLE
Crafting Multi Block Is Broken

### ISSUE THREAD

**Issue by DinnerBeef** [TechReborn/RebornStorage#171]
https://s.dinnerbeef.com/gOXe5/deRIjAJi61.mp4/raw

- It does not deform right
- You can click past the number you have. 
   - "I was using an auto clicker to make it happen is that video but was able to do it without an auto clicker"

Mod Version: rebornstorage-1.18.2-4.0.5
Pack: Direwolf20 1.18 - 1.2.0

**Comment by Ayutac** [comment]
I'm not trusting that link. Also, can you describe your bug more? What Multiblock? What deforming?

**Comment by DMNerd** [comment]
#169

**Comment by gigabit101** [comment]
Fixed in 4.0.10
