### ISSUE TITLE
Suggestion: Keybind to open Ultimate Crafting Grid

### ISSUE THREAD

**Issue by Poke5555** [TechReborn/RebornStorage#172]
refined storage has keybinds to open the other grids so i was hoping you could add this as a feature to the ultimate grid,
thanks for  making this mod, i really enjoy it :D

**Comment by gigabit101** [comment]
Already added, Just waiting on pushing a release

**Comment by Poke5555** [comment]
awesome thanks :D

**Comment by gigabit101** [comment]
Fixed in 4.0.10
