### ISSUE TITLE
crafter manager 

### ISSUE THREAD

**Issue by opaplays** [TechReborn/RebornStorage#176]
Hello 

I keep crashing when trying to access the crafter manager when it is connected to the reborn storage multiblock, i am on a server and i tested in single player as well still same thing, when on the server it just disconnects me and on single player it makes minecraft stop responding and then im back to the menu to select single player, i don't know why this is happening hopefully someone can help.

here is my client latest log as it doesn't say anything on the server log
[latest.log](https://github.com/TechReborn/RebornStorage/files/8804287/latest.log)

**Comment by gigabit101** [comment]
There is nothing in the log you provided about RebornStorage

**Comment by opaplays** [comment]
well just figured out it is your mod as if i disconnect a 16x16x16 multiblock and create a smaller one i don't get disconnected from single or multiplayer
