### ISSUE TITLE
Crafing Multiblock Not forming [1.18.2-4.0.12]

### ISSUE THREAD

**Issue by Remixed-Witch** [TechReborn/RebornStorage#177]
Not able to make multiblock, simply states that certain blocks are not meant for the frame or interior, including one time where it tried to say that air outside the multiblock is the interior
![DlVBTbaFno](https://user-images.githubusercontent.com/101052267/174503700-61031424-d3e3-45c9-9883-dc2c5abc725a.png)
![javaw_v1KuG1dsO9](https://user-images.githubusercontent.com/101052267/174503701-237fd843-4e16-4e9c-9f02-c4c6abf7fea7.png)
![javaw_qXG6OjwBHG](https://user-images.githubusercontent.com/101052267/174503702-31647b29-74c2-46ba-a8af-63b99f9c4f4f.png)
![javaw_7FO8mwgFNH](https://user-images.githubusercontent.com/101052267/174503703-65439d11-fdec-48d2-9800-cda9cd268f43.png)
.

**Comment by LocoCubano** [comment]
Having the same issue its looking at a block outside the space and calling it invalid when making a 5x5x5

I tried making a 16x16x16 and It tells me: Machine is too large, it make be at more 16 blocks in the x direction.

I checked with the measuring tape from chisel & bits it is indeed 16x16x16

I also tried making the smallest one allowed to my recollection which is 3x3x4 and that also reported that an air block outside the machine was invalid interior. 

16x16x16
![16by16by16](https://user-images.githubusercontent.com/25106883/174521311-7f5cd938-d9ba-4e95-8762-3ca4eb21f6aa.png)

3x3x4
![3by3by34](https://user-images.githubusercontent.com/25106883/174521325-e665f3ac-e91b-414b-99de-17c4f7bff281.png)

**Comment by richie3366** [comment]
I got the same issue as @Remixed-Witch, restarting the game did solve it

**Comment by LocoCubano** [comment]
> I got the same issue as @Remixed-Witch, restarting the game did solve it

Oh yeah a restart did make the machine I left intact function, ok neat

**Comment by richie3366** [comment]
Actually, that's a bit of a bummer because I was on my way to figure how to solve it myself and propose a fix to the author.
But I managed to [fix another bug](https://github.com/TechReborn/RebornStorage/pull/178), so it was not for nothing.

**Comment by Fenekhu** [comment]
I just got this, where it tried to tell me a block outside of the structure wasnt valid for the interior. That was after I rebuilt it because it wasn't crafting anything. As I was breaking it apart, even when there was only a single block left that was just a frame, i could still right-click on it and it would show me the UI it had before breaking it.

**Comment by gigabit101** [comment]
Log out and back in, For some reason the multiblock does not update the client sometime and I have yet to figure out why

**Comment by z1043206827** [comment]
I am also facing this issue. How do I address it

**Comment by gigabit101** [comment]
What version of the mod are you using and for what Minecraft version?

**Comment by z1043206827** [comment]
> 您使用的是哪个版本的模组以及哪个我的世界版本？

minecraft1.19.2 .mod 5.0.3
![QQ截图20230602113224](https://github.com/TechReborn/RebornStorage/assets/66665654/7b14e9d7-b4c4-4a5d-a2ae-467503076b91)

**Comment by gigabit101** [comment]
Have you tried logging out and back into the world?
