### ISSUE TITLE
using storage upgrader on fluid tanks requires to empty, destroy and place the tank to get the full capacity

### ISSUE THREAD

**Issue by rapus95** [TechReborn/RebornStorage#181]

**Comment by gigabit101** [comment]
Storage upgrader? I think you are in the wrong place

**Comment by rapus95** [comment]
@gigabit101 same here, might you move it please?

**Comment by modmuss50** [comment]
Feel free to open new issues at https://github.com/TechReborn/TechReborn/issues its prob easier than moving it.
