### ISSUE TITLE
No keybind for super wireless grid

### ISSUE THREAD

**Issue by shrad1994** [TechReborn/RebornStorage#185]
Someone reported this issue on the ATM8 issues page, figured I'd send it your way

**Comment by gigabit101** [comment]
Not sure why It would not be showing up as we do add one, Will look into this when I find the time

**Comment by volrathstormborn** [comment]
Yeah ran into the same issue.  Got the "The mod does not have a configs registered or is not using Forge's config system."

Under the instance main folder the "options.txt" does not have the two lines for the keybind settings.  I had these in 1.18.2:

key_key.rebornstorage.openWirelessCraftingGrid:key.keyboard.z:SHIFT
key_key.rebornstorage.switchModeWirelessCraftingGrid:key.keyboard.g:CONTROL

They are not present in 1.19.2

**Comment by Smario9000** [comment]
so its still not fix? hmmm i wonder if i can just add them

**Comment by gigabit101** [comment]
Todays release fixed this but broke loading on dedicated servers, Expect a new build soon

**Comment by Smario9000** [comment]
ok ill check back later to see when the new new update comes out

**Comment by gigabit101** [comment]
Fixed in 5.0.2

**Comment by Adzeiros** [comment]
How does one fix this? The only release I see is from 2019?

**Comment by shrad1994** [comment]
Thank you guys :)
