### ISSUE TITLE
Minecraft 1.19.2 server crash

### ISSUE THREAD

**Issue by Realever** [TechReborn/RebornStorage#187]
hi,
i updated the mod Reborn Storage to the version 1.19.2-5.0.1 and my server crash on start up.The client start without any problem but only the server is the problem.Here is the crash log: [Pastebin](https://pastebin.com/e8kBeyKG).
Minecraft version: 1.19.2
Reborn Storage version: 1.19.2-5.0.1
Forge: 1.19.2-43.2.0

**Comment by gigabit101** [comment]
Fixed in 5.0.2
