### ISSUE TITLE
External Storage integration for the crafting multiblock

### ISSUE THREAD

**Issue by catt0** [TechReborn/RebornStorage#19]
A request to improve handling of lots of recipes:
Integration for the External Storage, so we can make a small network which just attaches an External Storage to the multiblock, so you can search the patterns in a Grid and pull them out directly.
If you currently do this, you just get the crafting options, but you can not pull the patterns itself out.

**Comment by modmuss50** [comment]
I plan to add a block that goes on the side of the multiblock that gives full inv access to allow piping in and out.

**Comment by gigabit101** [comment]
same as #6
