### ISSUE TITLE
Mutli block storage won't form.

### ISSUE THREAD

**Issue by BIBLOFFXI** [TechReborn/RebornStorage#193]
I have tried all sizes. I have restarted pack and server. Playing atm8 latest version.[https://imgur.com/PK5TApk](url)

**Comment by BIBLOFFXI** [comment]
I got it to form by making sure nothing was touching it on any side. Log out and back in and it formed.

**Comment by gigabit101** [comment]
Yeah, it's a packet issue, I believe I have fixed this in 1.20 however I have never managed to get this to happen to me...
