### ISSUE TITLE
Mod just does not work in ATM8.

### ISSUE THREAD

**Issue by Max-Pare** [TechReborn/RebornStorage#196]
Game version 1.19.2
Mod version 1.19.2-5.0.3
I've spent about 3 hours building and re-building the crafting multiblock, I followed tutorials and wikies for the building patterns of the multiblock, 1 time out 10 the multiblock builds successfully, the other 9 times it just does not work and gives the message "Block - is not valid for interior of multiblock". Sometimes (not always) if the configuration worked and one block is broken and re-placed, it suddendly doesn't work even if it's identical to the previous working configuration.
Other times, if the multiblock works as intended and is then expanded in any axis, it stops working and even after restoring the shape to the working one, it does not work.
Lastly, I had one multiblock constantly say that the "Multiblock cannot be larger than 16 blocks on the Z axis" for a 6x6x3 crafter.

I tried a suggestion from reddit that says to keep the entire multiblock inside one chunk, but that does not fix the issue.

I've also tried building it in a chunk with nothing on it (as in no other machines or refined storage blocks) but no luck.

**Comment by gigabit101** [comment]
Can you build it again and try restarting your game?, If it is the bug I think it is then that should fix it.

**Comment by Max-Pare** [comment]
> Can you build it again and try restarting your game?, If it is the bug I think it is then that should fix it.

Yep that did it. Seems like reloading the world after building the multiblock fixes it, not necessarily reloading the entire game but I haven't done any extensive testing.

**Comment by gigabit101** [comment]
Yeah, For some reason the client does not get the packet from the server telling the client the multiblock is valid, I have never been able to get this to happen to me sadly
