### ISSUE TITLE
multi-block crafter vs ExtraStorage Crafters

### ISSUE THREAD

**Issue by penturt** [TechReborn/RebornStorage#197]
Just trying to figure out if there is any benefits of using the multi-block crafter over ExtraStorage [https://www.curseforge.com/minecraft/mc-mods/extrastorage](url) crafters?

**Comment by gigabit101** [comment]
I end up using both, Multiblock for crafting table recipes as it can hold a stupid amount of recipes and extra storage for inserting into machines
