### ISSUE TITLE
Multiblock crafter menu issue

### ISSUE THREAD

**Issue by nicogb2007** [TechReborn/RebornStorage#198]
I'm on the modpack ATM9 and the menu is completly glitched.
It does not show the paterns in the crafter and does not show the inventory(see the screen bellow)
![image](https://github.com/TechReborn/RebornStorage/assets/107760410/47acbf16-0e2c-449b-87b0-9b1339164190)

**Comment by Minecrafter8001** [comment]
i have this issue too

**Comment by gigabit101** [comment]
restart your game or if on server disconnect and reconnect

**Comment by illusionoo** [comment]
> restart your game or if on server disconnect and reconnect

i have same issue with 1.20.1-5.0.7, restart/reconnect does not work, i tested it on only 2 mods,  reborn storage n RS. 
but, if i rollback to version 1.20.1-5.0.6 the issue gone. 
bad english, holp it help.

**Comment by Bluemethyst** [comment]
Same issue here on ATM9, anyone know the issue or how to fix?

**Comment by gigabit101** [comment]
restart your game or log out and back into the server
