### ISSUE TITLE
Crash, World broken

### ISSUE THREAD

**Issue by Techatar** [TechReborn/RebornStorage#2]
I have a crash! Crashed when placing down my crafting storage block. I have the log file saved if you need it. If so where do you want it uploaded?
EDIT It's completely broken my world.
CRASH REPORT - http://pastebin.ca/3754539
[crash-2017-01-07_01.06.04-client.txt](https://github.com/TechReborn/RebornStorage/files/691150/crash-2017-01-07_01.06.04-client.txt)

**Comment by gigabit101** [comment]
Update reborncore

**Comment by modmuss50** [comment]
This is still an issue, im missing a null check.

**Comment by modmuss50** [comment]
https://github.com/TechReborn/RebornStorage/blob/master/src/main/java/RebornStorage/tiles/TileMultiCrafter.java#L116 might be null
