### ISSUE TITLE
Storage Disks Cannot Be Split Back Into Storage Part/Housing [1.20.1-5.0.7]

### ISSUE THREAD

**Issue by raelHoncin** [TechReborn/RebornStorage#203]
Shift/Sneak right clicking does not seperate storage parts from housings as it does in Refined Storage, meaning you cannot combine remove and combine disks once placed into a housing.  (Tested with all Storage disks added and all are effected except the following 256k fluid, 
1024k fluid, 
4096k fluid 
witch split as intended)

**Comment by gigabit101** [comment]
Added to my TODO list

**Comment by gigabit101** [comment]
dupe of #179
