### ISSUE TITLE
Multiblock crafter no pages?

### ISSUE THREAD

**Issue by FrAmed46** [TechReborn/RebornStorage#206]
I made a multiblock crafter on my server but the slots dont exist. It also allows you to switch pages endlessly
image:
![image](https://github.com/user-attachments/assets/b61c9089-6342-402a-907d-e7085e0a53d7)
you can see its blank and it has 54 pages out of 0, something impossible for a 3x3x3 (i changed the minimum in the config)
I tried building it a different size but nothing
Mc details:
MC Version: 1.20.1
mod version: 5.0.7
Server host: Aternos

**Comment by FrAmed46** [comment]
SOLVED!!!
For anyone else who sees this, i rejoined and it magically worked

**Comment by gigabit101** [comment]
Yeah for some reason sometimes the packet does not get to the client and re-logging fixes the issue
