### ISSUE TITLE
IO Port can't go in top or bottom of crafter multiblock in MC 1.12?

### ISSUE THREAD

**Issue by mycroftjr** [TechReborn/RebornStorage#207]
Why were https://github.com/TechReborn/RebornStorage/blob/1.12/src/main/java/me/modmuss50/rebornstorage/tiles/TileMultiCrafter.java#L51 and https://github.com/TechReborn/RebornStorage/blob/1.12/src/main/java/me/modmuss50/rebornstorage/tiles/TileMultiCrafter.java#L58 made to prevent the IO Port from being in the top or bottom face of the crafter multiblock in MC 1.12? In fact, why are the top and bottom even handled any differently than the other 4 sides?

**Comment by gigabit101** [comment]
Its the same Multiblock API I use for other projects so it's designed to be used that way
