### ISSUE TITLE
Critical bug(+dupe) with Implosion Compressor

### ISSUE THREAD

**Issue by Rukifox** [TechReborn/RebornStorage#21]
Hello guys, i found two unpleasant bugs with implosion compressor. (Minecraft 1.10.2/2.1.6.180)

1. Machine needs multi-block structure, but machine works without it. 
2. When you "standing" in machine's inventory and someone destroys it, GUI will not close. All resources drops, but in GUI they also remain.

*Video*: https://youtu.be/CFDDYbHhVtg

_Sorry for my very bad english, i'm from Russia, hello .__._

**Comment by modmuss50** [comment]
I think this is the wrong mod
