### ISSUE TITLE
ENHANCEMENT Faster interfaces

### ISSUE THREAD

**Issue by ghost** [TechReborn/RebornStorage#23]
Possibly you could add an interface like the one from ae2 that is instantaneous transfers.
It would be useful for things like mass dumping from ender chests, farms, and mining setups which are limited by the input/output rate of the current interface in refined storage.

**Comment by modmuss50** [comment]
I wonder if we could make better speed upgrades?

**Comment by gigabit101** [comment]
Maybe or just add a block with inv and as soon as something enters it put it in RS

**Comment by gigabit101** [comment]
Need to get around to adding the inv controler to allow inserting of items and the power tap for single connection point aswell

**Comment by gigabit101** [comment]
I might work on that today

**Comment by modmuss50** [comment]
Right now this isnt possible without RS adding an API. So ill leave this open until I get a response.

**Comment by modmuss50** [comment]
Not possible. Also the interface is instant.
