### ISSUE TITLE
Restarting world Problem

### ISSUE THREAD

**Issue by Daihok41** [TechReborn/RebornStorage#27]
Everytime I restart my world i have to break a piece of cable coming from reborn storage to my refine storage then replace for it to load my patterns that are in reborn storage.

**Comment by gigabit101** [comment]
1.10 or 1.11

**Comment by modmuss50** [comment]
Did we even finish the 1.11 port??

**Comment by gigabit101** [comment]
I dont remember... lol

**Comment by gigabit101** [comment]
I dont have this issue in my ssp world nor after I moved the world to local hosted server so I dont no what is doing it

**Comment by BrianEdmonds** [comment]
I've been working around this by attaching my multiblock crafter to the RS system via a relay with a lever on it. Still effectively breaking the connection, but a bit cleaner to work with.

**Comment by gigabit101** [comment]
I still can not reproduce this issue mine work fine every time I log into my world

**Comment by scotty9090** [comment]
I have the same problem.  It didn't happen in Sky Factory 3 but in my new world need to go through the cable breaking exercise for the RS system to see my patterns.

**Comment by RogueRaiden** [comment]
Im also seeing the same problem, have to break a cable to get it to reconnect after my server does its restart.
