### ISSUE TITLE
Crafter will not work

### ISSUE THREAD

**Issue by ChillyCZDog** [TechReborn/RebornStorage#31]
I have tried redoing the crafting recipes. Tried rebuilding it. I can put patterns in but when i try to have it craft something it will not start. It comes up in the crafting monitor.

**Comment by modmuss50** [comment]
Do you have a CPU in the block?

**Comment by ChillyCZDog** [comment]
yes 18 and 9 pattern storage blocks.

**Comment by ChillyCZDog** [comment]
so... any ideas what is going on?

**Comment by gigabit101** [comment]
nope It works fine In my SSP world and in dev so....

**Comment by ChillyCZDog** [comment]
the one block craftier is not working ether. (the one from refined storage)

**Comment by modmuss50** [comment]
post to their github.

**Comment by Prospector** [comment]
did you make the pattern in the pattern encoder block or the pattern terminal?
