### ISSUE TITLE
Laggs out server then crash

### ISSUE THREAD

**Issue by CamaroKing59** [TechReborn/RebornStorage#32]
server keeps lagging when ever the multiblock is active

https://pastebin.com/KyX1bUj8 

Reborn Storage version: 1.10.2-1.0.2.29
Refined Storage Version: 1.2.25
Forge Version: 12.18.3.2254

**Comment by CamaroKing59** [comment]
it has something to with the oredict on the autocrafting patterns

**Comment by gigabit101** [comment]
we use the RefinedStorage api for this all the auto crafting code is there side

**Comment by gigabit101** [comment]
@way2muchnoise this yours?

**Comment by way2muchnoise** [comment]
Well building patterns is our code, but that should only be called on network rebuild (power out/disconnects). Could be that you guys are calling this a little bit to often?

**Comment by modmuss50** [comment]
Your pull request fixed it. I guess it's time to
take another look at it

**Comment by CamaroKing59** [comment]
ok i figured out that it is a power issue the bigger it is the more power it consumes and it would lag out my server and my single player when the power would fluctuate like everytime the system turns back on it would lag out the server now if i put creative power to it which gives it more then enough power we dont have any issues at all so i dont if there a bug in it or not

**Comment by way2muchnoise** [comment]
Every time power goes out RS cycles, this is something that is in the works to be fixed.

**Comment by CamaroKing59** [comment]
ok ya ive just been doing some testing and ididnt know if you guys knew or not

**Comment by CamaroKing59** [comment]
so is there any idea when this would be fixed or is it something thats going to take a while

**Comment by gigabit101** [comment]
we have no idea as this is a Refined Storage issue

**Comment by modmuss50** [comment]
Try make sure you system as enough power to keep up, or try multiple smaller multiblocks
