### ISSUE TITLE
Multiblock Crafter not respecting FTB Utilities chunk claiming (1.0.1.27, 3.4.3, respectively)

### ISSUE THREAD

**Issue by TherminatorX** [TechReborn/RebornStorage#34]
Found that while the chunk claiming for another player's base was working (couldn't access chests/RS grid), I was able to open up their Reborn Storage crafting multiblock and take/move patterns inside.

Discovered in the Sky Factory 3 modpack, version 3.0.8, for MC 1.10.2

Willing to test mods in standalone environment if necessary.

**Comment by gigabit101** [comment]
Yeah this is because its not handled like a normal TileEntity as its a muliblock there is not alot we can do about this

**Comment by modmuss50** [comment]
I think I have an idea why it's not working.

**Comment by TherminatorX** [comment]
Draconic Evolution energy storage cores and Extreme Reactors..reactors...are properly inaccessible, and I'm 90% sure they use multiblock code

**Comment by modmuss50** [comment]
I dont think is something I can fix. Come back if im wrong.
