### ISSUE TITLE
Extra Utilities 2 Builders Wand Dupes Blocks

### ISSUE THREAD

**Issue by RogueRaiden** [TechReborn/RebornStorage#35]
Exactly what the title says. Builders Wand copies the blocks without removing them from inventory.

extrautils2-1.10.2-1.4.1
RebornStorage-1.10.2-1.0.3.30

**Comment by modmuss50** [comment]
I don't see how it could be our issue. Does it happen with other blocks??

**Comment by gigabit101** [comment]
extrautils2 builders wand will dupe everything atm this is his side

**Comment by RogueRaiden** [comment]
oh really? i didn't seem to have any problems with other blocks. Plus the Actually Additions drill with the 3x3 augment doesn't affect the Reborn Storage blocks. Since my knowledge with java coding is very limited, i took both of those factors and thought "maybe the blocks aren't coded right?" and just put the issue here. But thanks guys, so far enjoying the mod.
