### ISSUE TITLE
Holding shift makes it go blue? (v1.0.3.30)

### ISSUE THREAD

**Issue by Boomflex** [TechReborn/RebornStorage#39]
http://i.imgur.com/EaEpTT5.png

Holding shift with it open and the background changes to blue?

Bug or intended?

**Comment by modmuss50** [comment]
I bet its an issue with one of the item being rendered (hint: try the blue items), try removing some of the patternts untill it doesnt happen.

**Comment by modmuss50** [comment]
I can work around this on our end if needed.

**Comment by Boomflex** [comment]
This is now doing it with an empty inventory.

http://i.imgur.com/xBSQdY4.png

**Comment by modmuss50** [comment]
huh, try without anything in the players inv?

**Comment by Boomflex** [comment]
Same as before, still blue? (which I actually like)

**Comment by modmuss50** [comment]
Humm ok, I will leave the issue open, if anyone one else reports it I will fix it our end.

**Comment by calloatti** [comment]
I have had this happen, never reported it.

**Comment by modmuss50** [comment]
Ok thanks, you should report things so they get fixed 👍

**Comment by gigabit101** [comment]
its the ender io soul bottles

**Comment by gigabit101** [comment]
if they are showing in JEI it will go blue with all of the GuiBuilder gui's

**Comment by Boomflex** [comment]
Does it without those in my inventory/JEI too?

**Comment by modmuss50** [comment]
It's an easy fix in the gui builder

**Comment by modmuss50** [comment]
Fixed with: https://github.com/TechReborn/RebornCore/commit/fce54cd0b95b575dc3341b9ab9d84a6b3d857b90

I will backport the fix to 1.10 soon.
