### ISSUE TITLE
[1.10.2] [RebornStorage 1.2.16] All Blocks Drop Meta 0 Variant

### ISSUE THREAD

**Issue by oitsjustjose** [TechReborn/RebornStorage#4]
See Title: All rebornstorage:multicrafter drop meta 0 when broken (Silk Touch or Sans)

Not a huge bug, but makes me stay in cheat mode for a while in case something happens! Let me know if you need more info, but it's not a crash so I don't see any need for a log upload.

**Comment by modmuss50** [comment]
Fixed with: https://github.com/TechReborn/RebornStorage/commit/50ce2984be1c167824009307de92f26d02163c8b
