### ISSUE TITLE
Crash when using the reborn storage multiblock

### ISSUE THREAD

**Issue by brad18** [TechReborn/RebornStorage#40]
I am currently running a SkyFactory 3 and one of the users has run into a problem with crafting something in refined storage. I noticed your mod was included in the crash report so I thought I'd post in here. Any ideas on what exactly is crashing the server in the crash reports below?

https://pastebin.com/evYdYknQ
https://pastebin.com/g9ZQe4w3

I can provide any extra info that you may need.
Thanks for your time.

**Comment by modmuss50** [comment]
Can he try putting all the patterns in a normal crafter from RS, and see if it still happens?

**Comment by brad18** [comment]
The player who had the issue hasn't been back but I took a brief look at the recipe which they claim didn't work and it now mysteriously works in both the refined storage crafter and rebornstorage crafter so I guess you can close this for now. I'll reopen if we get any more issues.

**Comment by modmuss50** [comment]
All development has moved to 1.12, it should fix now.
