### ISSUE TITLE
Cannot Compile

### ISSUE THREAD

**Issue by GuardedAirplane** [TechReborn/RebornStorage#42]
I tried to compile the mod on June 18, 2017 at 14:15 EST and received a compilation error:

`Task :compileJava
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/multiblocks/MultiBlockCrafter.java:8: error: cannot find symbol
import com.raoulvdberge.refinedstorage.api.network.INetworkMaster;
                                                  ^
  symbol:   class INetworkMaster
  location: package com.raoulvdberge.refinedstorage.api.network
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/multiblocks/MultiBlockCrafter.java:208: error: cannot find symbol
        public INetworkMaster network;
               ^
  symbol:   class INetworkMaster
  location: class MultiBlockCrafter
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/multiblocks/MultiBlockCrafter.java:236: error: cannot find symbol
        public void onConnectionChange(INetworkMaster network, boolean state, BlockPos pos) {
                                       ^
  symbol:   class INetworkMaster
  location: class MultiBlockCrafter
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/tiles/TileMultiCrafter.java:5: error: cannot find symbol
import com.raoulvdberge.refinedstorage.api.network.INetworkMaster;
                                                  ^
  symbol:   class INetworkMaster
  location: package com.raoulvdberge.refinedstorage.api.network
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/tiles/TileMultiCrafter.java:10: error: cannot find symbol
import com.raoulvdberge.refinedstorage.apiimpl.network.node.INetworkNodeHolder;
                                                           ^
  symbol:   class INetworkNodeHolder
  location: package com.raoulvdberge.refinedstorage.apiimpl.network.node
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/tiles/TileMultiCrafter.java:32: error: cannot find symbol
public class TileMultiCrafter extends RectangularMultiblockTileEntityBase implements INetworkNodeProxy, INetworkNodeHolder {
                                                                                                        ^
  symbol: class INetworkNodeHolder
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/tiles/NetworkNodeMultiCrafter.java:5: error: cannot find symbol
import com.raoulvdberge.refinedstorage.api.network.INetworkMaster;
                                                  ^
  symbol:   class INetworkMaster
  location: package com.raoulvdberge.refinedstorage.api.network
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/tiles/TileMultiCrafter.java:123: error: cannot find symbol
        INetworkMaster master;
        ^
  symbol:   class INetworkMaster
  location: class TileMultiCrafter
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/tiles/NetworkNodeMultiCrafter.java:75: error: cannot find symbol
        protected void onConnectedStateChange(INetworkMaster network, boolean state) {
                                              ^
  symbol:   class INetworkMaster
  location: class NetworkNodeMultiCrafter
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/init/ModItems.java:6: error: cannot find symbol
import com.raoulvdberge.refinedstorage.block.EnumItemStorageType;
                                            ^
  symbol:   class EnumItemStorageType
  location: package com.raoulvdberge.refinedstorage.block
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/tiles/TileMultiCrafter.java:191: error: cannot find symbol
                if (node.getHolder().world() == null) {
                        ^
  symbol:   method getHolder()
  location: variable node of type NetworkNodeMultiCrafter
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/tiles/TileMultiCrafter.java:192: error: cannot find symbol
                        node.setHolder(this);
                            ^
  symbol:   method setHolder(TileMultiCrafter)
  location: variable node of type NetworkNodeMultiCrafter
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/tiles/TileMultiCrafter.java:206: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/tiles/TileMultiCrafter.java:211: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/tiles/TileMultiCrafter.java:216: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/tiles/TileMultiCrafter.java:221: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/godfreyhendrix/Downloads/RebornStorage-master/build/sources/main/java/RebornStorage/tiles/NetworkNodeMultiCrafter.java:21: error: constructor NetworkNode in class NetworkNode cannot be applied to given types;
                super(crafter);
                ^
  required: World,BlockPos
  found: TileMultiCrafter
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
17 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 1s
5 actionable tasks: 3 executed, 2 up-to-date`

I ran `gradle setupDecompWorkspace` prior to `gradle build` so I don't think it is missing a dependency.

My goal is to get a 1.11.2 version of the mod which the source code seems to make so if you have a compiled version that would be great.

**Comment by modmuss50** [comment]
the RS api might have changed, and the 1.11.2 was never finished. and isnt supported.

**Comment by GuardedAirplane** [comment]
Ok, cool. Is there a more recent source package for this mod that makes use of the new api?

**Comment by modmuss50** [comment]
Nope, thats it. You can try and fix it yourself if you really want it that badly.
