### ISSUE TITLE
Multi block crafter recipes not recognized

### ISSUE THREAD

**Issue by Tornac** [TechReborn/RebornStorage#43]
Using Direwolf20 pack version 1.12.1 and added RebornStorage.

Patterns/Recipes placed in the multi block crafter (min size 3 high, 2x2 with 1 cpu and 1 storage) do not show up in the refined storage system after starting a single player world. Currently I can only fix the issue by breaking and replacing the RS controller block. Issue re-occurs every time the world is shut down and loaded later.

**Comment by modmuss50** [comment]
All development has moved to 1.12, it should fix now.
