### ISSUE TITLE
MultiBlockCrafter still decreases performance

### ISSUE THREAD

**Issue by Karaclysm119** [TechReborn/RebornStorage#44]
Running Sky Factory 3 version 3.0.13
Reborncore: 2.13.6.142
RebornStorage: 1.0.3.30
RefinedStorage: 1.2.26

In my world i built a 16x16x16 MultiBlockCrafter with 3 crafting storage and the rest of th einterior CPUs. upon reopening the world i would either crash, enter the world except none of the blocks would load, or load into the world fully with an extreme delay on any action i would do. The only way i could solve the issue and regain control of my world was by disconnecting the MultiBlockCrafter via deleting the connecting cable in MCedit.

**Comment by modmuss50** [comment]
All development has moved to 1.12, it should fix now.

**Comment by DBotThePony** [comment]
https://github.com/raoulvdberge/refinedstorage/issues/1421 (comment)
