### ISSUE TITLE
Add a config to power consumption

### ISSUE THREAD

**Issue by kane-thornwyrd** [TechReborn/RebornStorage#45]
Hello guys,

Thank you for this beautiful work,

Can you add a way to configure the power consumption of each part, please ?

_Use case:_
My modpack is quite light on tech, and an whole Immersive Engineering diesel generator
is not enough to feed a poor 4x4x4, which I find quite ridicule.

**Comment by xortly** [comment]
I have the same issue. The power consumption is huge !

**Comment by PessimisticBastard** [comment]
Yeah, power consumption is a bit ridiculous. I'd like a config as well. 13,600 rf/t for 9 crafting CPUs and 9 crafting storage is just way too much. Putting a creative power supply on the bottom of my system for now.

Edit: Okay, so I reconnected the multiblock to my system after putting in the creative power source. Now it's reading a much more reasonable 1215 rf/t (for just the multiblock). Perhaps this is a bug that you can't provide enough power for yours with an IE Diesel Gen (I'm assuming you are creating enough biodiesel to keep it running)?

**Comment by gigabit101** [comment]
Yes this is on my todo list. Just after we get it stable.

**Comment by zlainsama** [comment]
I just built a 7x7x7 crafter multiblock with 50 cpu and 75 storage, it costs around 300k rf/t, which is far beyond the default capacity setting of the refined storage controller.

**Comment by modmuss50** [comment]
Right, ok. So the current issue is the RS api only allows me to supply an int value for the power. This means the minimum power I can make it require is 1 per block. If people have issues with the power using too much let me know and ill have to figure something out.

**Comment by zlainsama** [comment]
What about a core block with calculated total power cost and other cost no power?
