### ISSUE TITLE
Support for processed patterns (Solderer) with Multiblock Crafter

### ISSUE THREAD

**Issue by SimpleConjugate** [TechReborn/RebornStorage#52]
Is there support to automate crafting using external machines such as the solderer, alloy smelter, etc?

This is doable with just refined storage crafter's, but I was unable to do it with the multiblock crafter.

**Comment by modmuss50** [comment]
No sadly that isn't possible. We might be able to add an upgraded crafter in the future though so I will leave this open.

**Comment by Paril** [comment]
So, is this still "open"? I'd love for some kind of Interface block to be added to the multiblock that allows it to be used as Processing Pattern storage too. It just needs to be an output-like block, like a port.
