### ISSUE TITLE
[1.12.1] Crash to title screen when trying to craft item: RebornStorage.tiles.TileMultiCrafter cannot be cast to com.raoulvdberge.refinedstorage.tile.TileBase

### ISSUE THREAD

**Issue by calloatti** [TechReborn/RebornStorage#54]
Made pattern for importer, place it in multiblock, try to craft one, crash.

https://paste.ee/p/iYXLe

**Comment by calloatti** [comment]
Recreated pattern, tried in normal crafter, it works, tried in multiblock, it works now.

**Comment by AllieWade** [comment]
Same crash (same error) in 1.12.2: I'd link the log, but the error ran so many times that the log exceeds Pastebin's limit.

I strongly suspect that in my case the crash occurs when I try to use the crafting monitor while the multiblock crafter is processing a job, but I haven't done extensive testing yet.

**Comment by modmuss50** [comment]
This is an issue with RS. Its assuming the tile is always an instance of its own TileBase

**Comment by raoulvdberge** [comment]
Not so fast there! You are extending RS'es own `NetworkNode` class (in the package `com.raoulvdberge.refinedstorage.apiimpl`, which is reserved for RS tiles and nodes, so casting to my own tile is not an unfair assumption! A fix on your side is to override `resetDirection` to get rid of the cast. Or, alternatively, implement your own network node correctly.
