### ISSUE TITLE
[1.12] Mixed up recipes

### ISSUE THREAD

**Issue by TheLimePixel** [TechReborn/RebornStorage#55]
Regular Storage Disks also have the recipes for Fluid Storage Disks, allowing them to be crafted with Fluid Storage Parts and making the Fluid Storage Disks unobtainable:
![image](https://user-images.githubusercontent.com/25333164/30785871-9621a550-a16d-11e7-9bb5-7aee52474640.png)

The same goes for the Parts:
![image](https://user-images.githubusercontent.com/25333164/30785882-c09777c4-a16d-11e7-9fb6-86067afe3a5d.png)

**Comment by gigabit101** [comment]
this was fixed a while ago
