### ISSUE TITLE
Reborn Storage Disks don't work with the Disk Manipulator

### ISSUE THREAD

**Issue by brisingraerowing** [TechReborn/RebornStorage#64]
Trying to put a Reborn Storage disk into a disk manipulator simply puts the disk into the output without moving any items from it. Disks from RS itself work perfectly fine.

**Comment by brisingraerowing** [comment]
I just moved a disk to a temporary system, and nothing shows up as being on the disk, even though the disk itself shows items on it.

Sadly, I am going to have to remove this mod, as it seems that nothing it adds works correctly right now.

**Comment by modmuss50** [comment]
Thanks for reporting the issue. I hope we can get it sorted out in the future.

**Comment by modmuss50** [comment]
Works fine for me. Please reopen if it is still an issue using the latest version of RS and RS
