### ISSUE TITLE
[1.12.2] Crash due to ClassCastException

### ISSUE THREAD

**Issue by SnowShock35** [TechReborn/RebornStorage#65]
#### Issue Details

- Minecraft 1.12.2
- Minecraft Forge 14.23.1.2555
- Refined Storage 1.5.24
- Reborn Storage 2.1.1.16
- Reborn Core 3.4.12.155

#### Issue Description

Intermediary crashes when auto-crafting within my Refined Storage system. The crash so far has occurred with two recipes (sugar cane > sugar and speed upgrades from extra utilities 2). 

The crash occurs when trying to craft an item a second time after crafting it once and it not doing anything. Perhaps to do with all those exceptions in the log. 

I'm using the Refined Storage and Reborn Storage crafting multi-block and I'm requesting from a crafting grid.

#### Issue Media

- [Log file](http://paste.feed-the-beast.com/view/31e04ec2)

**Comment by modmuss50** [comment]
Thanks for reporting. This one seems a strange one. I’ll look into it later. This also reminds me that I had planned to rewrite the mod.

**Comment by SnowShock35** [comment]
Yeah. I saw the latest changelog after I reported it. Thanks modmuss.

**Comment by modmuss50** [comment]
Humm, @raoulvdberge mind taking a look at this? I dont see how this could be our issue, it looks like you are trying to assume that all add-on mods should use TileBase, but that isnt possible in my case?

**Comment by raoulvdberge** [comment]
https://github.com/TechReborn/RebornStorage/issues/54#issuecomment-339055991
