### ISSUE TITLE
Most recent version of the mod rejects Minecraft 1.12.1

### ISSUE THREAD

**Issue by mycroftjr** [TechReborn/RebornStorage#67]
I'm playing Modern Skyblock 2 version 2.4.4 (Minecraft 1.12.1 forge-14.22.1.2484) and tried to surgically update just RebornStorage to a rewritten version of Reborn Storage (3.0.1.26) to hopefully eliminate the annoying bugs, but on launch, Minecraft complains that the mod is not compatible with this version of Minecraft?

Sorry if I'm just missing some vital knowledge of forge, but the last 5 versions of this mod have been marked compatible with all 1.12 sub-versions, so I would have expected this to work? Do I need to update forge to a version at least as large as specified in project.properties?

**Comment by mycroftjr** [comment]
It appears to work (Minecraft loads and I can enter my world and interact with the crafting multiblock) when I recompile (with "gradlew build") after editting project.properties to minecraft-version: 1.12 and forge version 1.12.1-14.22.1.2484! You might try to build against the earliest Forge version you can (like RebornCore seems to?) instead of increasing the forge version with every update?

**Comment by modmuss50** [comment]
I can easily fix this by setting the mc version in the @Mod annoation
