### ISSUE TITLE
Extra disks in 1.10.2

### ISSUE THREAD

**Issue by codetaylor** [TechReborn/RebornStorage#7]
Are the extra disks planned to come back to the 1.10.2 version?

**Comment by modmuss50** [comment]
We had planed to, but due to refined storage not having the API's for it in 1.10 we cannot. We asked for the APIs to be added into 1.11, and they have. So when we move to 1.11 there will be larger disks.

**Comment by codetaylor** [comment]
Ok, thank you. :)
