### ISSUE TITLE
Multiblock crafter not forming correctly in multiplayer world

### ISSUE THREAD

**Issue by iconmaster5326** [TechReborn/RebornStorage#72]
I'm trying this in the DW20 modpack, version 1.3.0, for MC 1.12.

In singleplayer, I'm putting together a simple multiblock crafter with 1 CPU and 1 storage. It works fine, I can open the thing's GUI no problem.

On a multiplayer server a friend of mine is hosting, I assemble the exact same multiblock, and when I click on it, it complains that "a block is invalid for the interior of the machine". I've tried building the thing in multiple locations with multiple shapes, and nothing works. Why does it form correctly in my world, but not on the server?

**Comment by modmuss50** [comment]
What version of the mod are you using?

**Comment by iconmaster5326** [comment]
Whatever's in the pack by default, which happens to be version 3.0.1.26. Reborn Core is at version 3.5.1.166, and Forge is at version 14.23.1.2555.

**Comment by modmuss50** [comment]
yeah, 3.0.2.32 fixed it.

**Comment by iconmaster5326** [comment]
Ah, grand, now I have to wait for the pack to update, I suppose. Glad to know it's fixed! Thanks a bunch!

**Comment by modmuss50** [comment]
Yeah, sorry about that.
