### ISSUE TITLE
Crafting unit disconnects on chunkloaded place

### ISSUE THREAD

**Issue by Boarschti42** [TechReborn/RebornStorage#73]
Hello, 

my crafting unit disconnects everytime i leave the server for a longer period or if i restart it. 
I attached a screenshot, so you know how i build it. There is also a relay with a button to reconnect it in case of a disconnect. Just removing one connection and reattaching it is enough. 

There is no dump or something like this, just the fact that it disconnects. 
We have 3 independent setups, everytime, the chunk with the unit is chunkloaded, it disconnects. If there isn't a chunkloader, all is fine. (cannot deactivate the chunkloader (chickenchunks) for this single chunk.

thank you

![2017-12-13_19 43 37](https://user-images.githubusercontent.com/27770844/33956220-31f52bc8-e03e-11e7-9d6e-5987ff1fd8c4.png)

PS: Version 1.10.2

**Comment by modmuss50** [comment]
1.10.2 is no longer supported. Sorry
