### ISSUE TITLE
Game Crash when interaction with Mekanism 

### ISSUE THREAD

**Issue by bthrom** [TechReborn/RebornStorage#74]
I had Mekanism universal cables running along the underside of my crafter  and it caused the game to crash but it was not right away had them there for a day or two but this found this in the crash-logs. Removed the universal cables from near the crafter and the world reloaded fine. 
Here is the crash report [https://pastebin.com/HpVK7dKV](url)

**Comment by modmuss50** [comment]
Update to the newer version of the mod.
