### ISSUE TITLE
Holding too many 256k (or better) drives at once can permanently break your game 

### ISSUE THREAD

**Issue by moonheart08** [TechReborn/RebornStorage#75]
![rip](https://user-images.githubusercontent.com/7806367/34223550-59ab1366-e585-11e7-85c9-31ee615300fe.png)

Yea.
RIP.
Reproducable using 10 filled 256k drives with an assortment of items. (Armor and Tools are probably the biggest suspects here)

**Comment by modmuss50** [comment]
yeah, that could be an issue. Basicly the drives are holding so much stuff the server cannot send it to the client. I think there is a way to fix this.

**Comment by raoulvdberge** [comment]
No. Shouldn't happen. You're overriding `Item#getNBTShareTag`. Some external mod isn't handling the share tag correctly and is sending the real tag instead.

Are you sure you got this while "holding" a drive?

**Comment by modmuss50** [comment]
I dont think this is an issue with our mod, also no reply so closing it.
