### ISSUE TITLE
Patterns Disappear

### ISSUE THREAD

**Issue by Moobien** [TechReborn/RebornStorage#76]
Hey guys, just upgraded from Version 2.1.1.16 to 3.0.0.36 for MC 1.12.2 and had 3 pages of patterns disappear. All the patterns I had in the RS machines were still there but the ones I had in my big crafter unit vanished,

**Comment by modmuss50** [comment]
Sorry about that. Have you got a backup of the old world I might be able to use to help improve the upgrader I wrote? This happened because the mod had a full rewrite for version 3.

**Comment by Moobien** [comment]
I may have a world i havent loaded since i updated if that will help but no backup of the one i lost my patterns on

**Comment by modmuss50** [comment]
Im going to close this, as the mod was a full rewrite and fixing it would be a right pain.
