### ISSUE TITLE
Add ability to separate storage part from housing

### ISSUE THREAD

**Issue by trittimo** [TechReborn/RebornStorage#78]
In Refined Storage, you can shift+right click with a storage disk in hand and get back the storage part/storage housing. This allows you to upgrade as you go, which is a nice feature.

It would be great if you could add this functionality to RebornStorage.

Also, it might be a good idea to only allow this when the storage disk is empty. Otherwise it could lead to accidental disk loss with millions of items.

**Comment by modmuss50** [comment]
That should be possible to add, I will do it as the same way that Refined Storage does it.

**Comment by omgimanerd** [comment]
Currently, the storage disk crafting recipes don't include Refined Storage's disk housing. How will the part separation work? Will the recipe be changed?
