### ISSUE TITLE
TPS Drop when using Large Disks

### ISSUE THREAD

**Issue by andr9528** [TechReborn/RebornStorage#79]
So i have a 16384K storage disk with 0.55 Mil items in it, when i put in my diskdrive my TPS drop to around 0.75.

The disk contains a lot of different items (Armours & Enchanted Books), but also a good amount of items that i have a lot of (Ores & their Mechanism breakdown parts).

Using a smaller disk (4096K) also seem to Drop the TPS (even when it barely contains any items), it does however not drop it as much as the bigger one

Depending on how many items are in the disk the mean tick time goes up, i only tested with 2 disk sizes, one (the bigger one) being the one i'm using, and the smaller as test data.
16384K --> Mean tick time of 1500-1900 ms
4096 --> Mean tick time of 200-400ms

Versions:
refinedstorage-1.5.31
Minecraft 1.12.2
forge-14.23.1.2590
RebornStorage-1.12.2-3.0.3.36
RebornCore-1.12.2-3.6.2.187-universal

Some more details can be seen i my post in this issue
https://github.com/raoulvdberge/refinedstorage/issues/1525

**Comment by andr9528** [comment]
Just tried downgrading the version to
RebornCore-1.12.2-3.5.1.166-universal
RebornStorage-1.12.2-3.0.2.32

While using a 1 Mil disk with 7k items in it, in the version mention above i had mean tick of 2900-3000 ms, while the newer version gives me a mean tick of 800-1000 ms

So something in the newer version has been changed to improve it.

Hope that helps some more :)

**Comment by andr9528** [comment]
Further testing have revealed that all disks, including Refined Storage disk has this TPS issue, their disk, just drop fewer TPS compared to Reborn Storage, as the TPS drops scales with size of disk.

**Comment by raoulvdberge** [comment]
This can be closed.
