### ISSUE TITLE
Crafter multiblock tries to use bone meal in recipe where it needs lapis

### ISSUE THREAD

**Issue by TheSulit** [TechReborn/RebornStorage#82]
Hey, I play the Direwolf20 1.12 modpack version 1.7.1 with the 3.0.3.36 version of Reborn storage and I got problems while crafting Aethium Solar Cells from Environmental tech, the Refined storage systems starts to reqiure bone meal when it is out of Lapis Lazuli. I got all my Patterns in the Reborn multiblock when I take the crafting recipe for bone meal out the refined storage finally tells me that it hasn´t enough lapis. In addtion my server crashe several times because the storage system tried to use different dye types for concrete it only worked when I took every pattern out except the one for black dye, idk if those two problems are related. I´m sorry that I can´t give u more info.

**Comment by TheSulit** [comment]
Okay nerver mind I tried to put the pattern in a normal crafter and i still have the same problem so probably not a mistake on your end, we are getting problems with other mods too so probably something else thats not working right.

**Comment by drcrazy** [comment]
bone meal and lapis are both registered in oreDictionary as dye. Maybe you set in your pattern to use oreDictionary?

**Comment by modmuss50** [comment]
Not our issue
