### ISSUE TITLE
Crafting Unit Stop Working on Server Restart [Multiplayer]

### ISSUE THREAD

**Issue by MrLightningBlaze** [TechReborn/RebornStorage#84]
Alright, this issue should be simple enough:
Whenever I build the crafting unit, any valid size, it works just fine at first.
I can use it as expected during normal usage, but it stops working once I restart my server.
This seems to be a MultiPlayer specific issue, as SinglePlayer I can leave the world and re-open it and it still works.
Once it stops working it won't let me open the GUI or craft anything with it, like its not even there, until I completely break every block of the machine and re-build it all completely.

Minecraft: 1.12.2
Forge: 14.23.1.2590 (It also happens with all versions up to 14.23.1.2605)
RebornCore: 3.6.4.194
RebornStorage: 3.0.3.36
Logs: No logs appear that are relevent to RebornStorage beyond normal loading logs

**Comment by modmuss50** [comment]
Does this happen after you log-out and then log back in. Or when the server is restarted?

**Comment by MrLightningBlaze** [comment]
I did further testing, it seems to happen every single time the chunk is unloaded, the server restart I am guessing is mearly just a cause of is unloading, it is leading me to guess something is wrong with saving the structure itself or re-initializing it when the chunk is loaded again. I should let you know I *do* have the cubicchunks mod for infinite world height and 16x16x16 chunks, but I tested removing it and making a new world without it, and it did the same thing for the crafter, becoming unusable when it is unloaded

**Comment by MrLightningBlaze** [comment]
It turns out it was an issue with my specific system, as even the same `.minecraft` copied onto any other computer are not having this issue, and a re-install of my system fixed it, so closing this issue.
