### ISSUE TITLE
[1.12.2] Extreme lag when inserting pattern and having lots of patterns

### ISSUE THREAD

**Issue by Paril** [TechReborn/RebornStorage#86]
It seems that network rebuilds are super expensive for these patterns. I found the issue to mainly be RebornStorage; even on loading my server with a crafter with 6 pages of recipes, it will take ~260 seconds to create all of the patterns. If they are all in regular Crafters, it will only take 25 seconds.

Original issue here: https://github.com/raoulvdberge/refinedstorage/issues/838#issuecomment-362879658

**Comment by modmuss50** [comment]
oh wow. What version of the mod are you using?

**Comment by modmuss50** [comment]
Ok, I have done some optimizations to the pattern rebuild. Hopefully this will help a bit. Can you try with a dev build from here:

https://jenkins.modmuss50.me/job/Team%20Reborn/job/RebornStorage/job/1.12/37/artifact/build/libs/RebornStorage-1.12.2-3.0.3.37.jar

If after trying that build it is only a little bit better, I have another idea on how I can make it even more efficient on the rebuild calls.

**Comment by Paril** [comment]
Hey there.

I am on RebornStorage-1.12.2-3.0.3.36.
I dunno if it's related/something you can fix, but it also takes several seconds to load a single page of recipes from a crafter on the client-side.

I'll test that out when I get a moment. I already moved all of the patterns to a Crafter and it's gonna be tedious to move everything back, haha. Do Crafters and the multiblock accept piped items?

**Comment by modmuss50** [comment]
Sadly not, It is on my list to add support to pipe patterns into the multiblock.

**Comment by Paril** [comment]
Also, I was wondering, what exactly causes the rebuilds to happen? I thought the network only did a rebuild when something was added or removed, but from the ticking report from LagGoggles it seems that the Controller block is doing rebuilds fairly often even though it has full constant power and no cables are being moved. I know that's more of a question for RS but maybe you have an idea?

As for the issue at hand, it seems to be fixed! Nice work! Here's a new Sampler if you want to take a look:
[nv.zip](https://github.com/TechReborn/RebornStorage/files/1693692/nv.zip)

It seems to even take *less* time than the regular wall of Crafters to rebuild now.

**Comment by modmuss50** [comment]
Awesome thanks for testing, I will push a new build to curse soon.

**Comment by modmuss50** [comment]
Ok, this has been reverted, when i have some more time again I will test it some more and see if I can can get it to work without breaking, unfortunately minecraft things weren't really designed to run in parallel.

**Comment by Paril** [comment]
Yeah, nothing that uses the regular API anyways. You'd think things like OreDict, etc would be okay async. I wonder, then, would it be possible to just keep the finished patterns in memory as long as the contents of the multiblock haven't changed? I noticed that with the regular Crafters, it will rebuild all of the patterns on a network rebuild even if the contents of the crafter haven't changed, but maybe this is a fundamental way that RS works (like on network rebuild, clear all patterns, visit all nodes to add patterns again).

**Comment by derrickmehaffy** [comment]
@modmuss50 just experienced a stall crash on `RebornStorage-1.12.2-3.1.0.50` placing a pattern into the multiblock crafter. 

My modpack is the `All the Mods 3` v 5.9.8c

Here is the stall file: 

[stall-2018-07-04_06.07.37-1.txt](https://github.com/TechReborn/RebornStorage/files/2162790/stall-2018-07-04_06.07.37-1.txt)

Let me know if you need anything else.

**Comment by adventurerok** [comment]
I have the same issue I think, my server lags out for about 20 seconds when I insert a pattern for the first time after a restart.

I'm using RebornStorage3.1.0.50 on the modpack FTB Revelation 2.1.0.

Here is a sample that I took during the lag out if that helps at all:
![rebornstoragelag](https://user-images.githubusercontent.com/1076294/42297766-ab6c97a6-7ff9-11e8-82fb-ce0844ca900c.png)

**Comment by modmuss50** [comment]
How big/how many patterns do you have?

**Comment by adventurerok** [comment]
I have 270 patterns, about 20 of which have ore dictonary enabled

**Comment by tgstyle** [comment]
Same issue here on 3.2.2.65, less than 100 patterns in the multiblock.

**Comment by tgstyle** [comment]
It's now getting to a point where the server shuts down. Here is the crash log from the watchdog.

https://gist.github.com/tgstyle/b7574bdbda17e0b4c7225ff93ed986bf

**Comment by MidoriKami** [comment]
I am also experiencing the same issues with extreme lag.

When inserting even one or two at a time extreme server lag follows, when inserting several very quickly using inventory tweaks shift and mouse over, the server completely locks up and may or may not crash.

RebornCore-1.12.2-3.10.0.332-universal.jar
RebornStorage-1.12.2-3.2.2.65.jar
refinedstorage-1.6.5.jar
refinedstorageaddons-0.4.2.jar

Minecraft 1.12.2, Playing the All The Mods 3, Pack Version 5.10.1

**Comment by modmuss50** [comment]
This has been fixed in newer versions of the mod, make sure you are using the latest 1.6 version of RS as well
