### ISSUE TITLE
Lost 2 full pages of patterns on upgrade to 1.12.2-3.0.4.39

### ISSUE THREAD

**Issue by NewtonAppolonius** [TechReborn/RebornStorage#87]
Forge Version: 14.23.1.2594

**Comment by modmuss50** [comment]
Interesting, I think I have an idea of what might of happened, I will take a look ASAP.

**Comment by modmuss50** [comment]
Do you happen to know what version you were running before? as any 2.x versions wont be compatible with updating?

**Comment by NewtonAppolonius** [comment]
Bit more info. Reverted to a backup.
Checked and all the patterns are there. This was post updating to 3.0.4.39
It had previously just crashed.:Let me dig out the crash report

**Comment by NewtonAppolonius** [comment]
[crash-2018-02-06_09.35.13-server.txt](https://github.com/TechReborn/RebornStorage/files/1698737/crash-2018-02-06_09.35.13-server.txt)

Hope that helps.

**Comment by NewtonAppolonius** [comment]
Apologies for the somewhat brisk first post. Was in a rush

The version I upgraded from is RebornStorage-1.12.2-2.1.1.16
My RebornCore is 1.12.2-3.4.12.155-universal

**Comment by modmuss50** [comment]
Ah, that helps a lot, I think I have an idea of what could be causing, it but im not sure. Ill get back to you in a bit.

**Comment by NewtonAppolonius** [comment]
No problem. Kudos on the rapid reply.
If it helps I think it crashed as I was setting up a new drawer from Storage Drawers.

**Comment by modmuss50** [comment]
Humm, I bet its to do with making the pattern rebuild parallel, I may have to revert my optimisation I did the other day.

**Comment by NewtonAppolonius** [comment]
I've reloaded and tested some of the backups from this morning.
I can only report that I cannot get the exact same symptoms from the restored backups.
But something weird is  going on in all of them.
One of them had no patterns available straight after load, a couple had patterns,
I could kick off a build job but the job would disappear as though completed but no output.
Sorry, that's all I have.

**Comment by Paril** [comment]
[crash-2018-02-05_18.31.00-server.txt](https://github.com/TechReborn/RebornStorage/files/1699754/crash-2018-02-05_18.31.00-server.txt)
[crash-2018-02-05_23.08.18-server.txt](https://github.com/TechReborn/RebornStorage/files/1699755/crash-2018-02-05_23.08.18-server.txt)

I was getting some random crashes last night too, RebornStorage-related, and def related to the async task. Damn, sucks because the new code was so fast and slick :(

**Comment by modmuss50** [comment]
yep, I think im gonna have to undo it, and then work on a new fix that doesnt break things.

**Comment by modmuss50** [comment]
ok, 3.0.5 has reverted the async pattern building and should fix this issue. I will work on re-adding the faster pattern building back after I have done some more testing of it
