### ISSUE TITLE
Recipe don't work eventhough its there

### ISSUE THREAD

**Issue by ghost** [TechReborn/RebornStorage#88]
I have Advanced capacitor recipe from advanced generators. For soem reason lead flux capacitor recipe don't work eventhough its there.

**Comment by modmuss50** [comment]
Can you try it in a normal refined storage crafter?

**Comment by ghost** [comment]
Doesn't work that way either.

**Comment by modmuss50** [comment]
It will either be an issue with your pattern or Refined Storage. Nothing to do with our mod sorry.

**Comment by ghost** [comment]
Ok thanks :)
