### ISSUE TITLE
My rs stystem doesn't show my crafting patterns

### ISSUE THREAD

**Issue by alinoe153** [TechReborn/RebornStorage#89]
Sky factory 3

I made the multiblock, can put my patterns in it, Connect the multiblock to my rs system but none of my crafting recipes appear. (I check the terminal setting for showing everything).

thx in advance

**Comment by araevingaming** [comment]
I created a post about this issue last November, having the exact same problems as you are. It was closed without a reply, so I messaged ModMuss and was informed that they are aware that the 1.10.2 version does not work, and I was told that they have no intentions of fixing it. 

This was my post: https://github.com/TechReborn/RebornStorage/issues/61

**Comment by alinoe153** [comment]
Thx for the reply :-)

I've dismantled the thing and made my crafters again...

**Comment by modmuss50** [comment]
Yeah, sorry to say that the 1.10 version will not be getting any support. The entire mod has been rewritten in 1.12 and now works a lot better.

**Comment by alinoe153** [comment]
No pb, thx for your good work.
