### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by CamaroKing59** [TechReborn/RebornStorage#9]
ok so i found a visual bug and i keep having to remove the patterns and put them back on page 2 and when i switch pages my inventory goes blank i was wondering if anyone else is haveing this problem and is there a fix or can there be a fix for it 

 

https://gyazo.com/5311302f29ae6a1885314575dc6286dc

 

https://gyazo.com/2d2fe84881171397ec902e301e3062ba

 

https://gyazo.com/48ef988ceb9adb471eb4426fc6ea2c5c

 

didnt even leave the inventory i just changed pages

**Comment by CamaroKing59** [comment]
the Current versions of the Mods are

Reborn Storage : 1.0.0.20
RebornCore : 13.0.102
Refined Storage : 1.2.17

**Comment by gigabit101** [comment]
Are you playing ssp or on a server??

**Comment by gigabit101** [comment]
I can not reproduce this issue

**Comment by oitsjustjose** [comment]
I've been using RebornStorage extensively in my singleplayer and I've not once encountered this issue using [this modlist](https://goo.gl/DV8p1T).

Not sure if it has anything to do with his mods or not.

**Comment by modmuss50** [comment]
Yeah, its a weird one.

**Comment by CamaroKing59** [comment]
I am playing on a server the pack I am playing is public on the curse launcher and so is the server you can test it on there it's the allied kingdom pack 2

**Comment by Peolr** [comment]
I can confirm it is happening to me as well. It has something to do with going through the list, changing storage blocks to cpu's, fixing the multiblock, and going through the list again. After a few times on smp it shows my inventory inside the multiblock and in the normal spot, but it doesn't dupe. Some times it also glitches out my inventory and only shows on a different page.

**Comment by CamaroKing59** [comment]
so i am not the only on having that issue

**Comment by InflamedSebi** [comment]
should be the same issue like #16 and is already fixed.
