### ISSUE TITLE
Use new quantity formatter

### ISSUE THREAD

**Issue by raoulvdberge** [TechReborn/RebornStorage#90]
RS 1.5.32 introduced a quantity formatter for formatting various numbers (like the ones on your storage disks).

Might be cool to have those on RebornStorage as well.

Accessible via `IRSAPI#getQuantityFormatter`.

See https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/src/main/java/com/raoulvdberge/refinedstorage/item/ItemStorageDisk.java#L103-L107 for an example.

**Comment by gigabit101** [comment]
Awesome will change it up tonight

**Comment by raoulvdberge** [comment]
It still has to be released on CF though, waiting for approval.

**Comment by gigabit101** [comment]
No time tonight will do tomoz

**Comment by gigabit101** [comment]
fixed in dev
