### ISSUE TITLE
Suggestion: Rounding out the crafting interface.

### ISSUE THREAD

**Issue by Karmacopper** [TechReborn/RebornStorage#91]
A few quality of life suggestions for consideration.

An extra switch in the **Pattern Grid** to automatically send _none processing_ patterns to the **Multi Block Pattern Crafter** when they are made.

If possible  a shift click when making a new pattern sends it to the player inventory, rather than just leaving it in the output slot. Maybe I should post this one to Refined Storage.

- Wireless Pattern Grid. Does exactly the same thing as the **Pattern Grid**, wirelessly.
- Crafter Grid. Manage your Crafter and **MBPC** patterns.
- Wireless Crafter Grid. As above, wirelessly.

**Comment by modmuss50** [comment]
I believe there is a mod to do all this already. Also out of scope of this mod.
