### ISSUE TITLE
SkyFactory 3--Reborn Storage for 1.10 [Ignoring Chunk Claims]

### ISSUE THREAD

**Issue by Hail4Gaming** [TechReborn/RebornStorage#92]
Couldn't find this anywhere online, but the Reborn Storage area is able to be accessed by anyone on a server on SkyFactory 3 v3.0.15. My chunks are claimed and I am OP but everyone else who is not can also access it, making it so they can steal my patterns if they wish. Has anyone mentioned this before?

**Comment by modmuss50** [comment]
1.10 is no longer supported, reopen if the issue is still in 1.12.

Sorry about that.
