### ISSUE TITLE
Crash with 1.12.2-0.5.33 Refined Storage update

### ISSUE THREAD

**Issue by xAlicatt** [TechReborn/RebornStorage#93]
Refined Storage 0.5.33 made some fairly significant changes and it's causing a crash with your mod. Refined Storage Addons version 0.3

https://gist.github.com/xAlicatt/5a6b3065a7b46cbbf0c20b0dcac1bdaf

**Comment by accessdenied0** [comment]
Crash general. Its a compat issue because of the changes made to the crafting-system.

In single player it loads up, but soon you open up a world [it crashes.](https://pastebin.com/DieECiDh)

**Comment by xAlicatt** [comment]
I swear I thought I tested that, but maybe I didn't. Anywho...I will edit the OP to reflect that. Thanks @accessdenied0

**Comment by accessdenied0** [comment]
To be fair, in this world, I already have a Reborn-Storage Crafting-chamber setup (4x3x3 with 1 page) with some recipes in it, from last version of Refined Storage (1.5.32). It makes it a perfect test world for this change. Maybe it doesn't crash without any setup or recipes.

**Comment by xAlicatt** [comment]
Makes sense actually :)

**Comment by modmuss50** [comment]
Looks like refined storage broke its API, should be an easy update on our end. I’ll look at it as soon as I get a chance.

**Comment by raoulvdberge** [comment]
Gigabit already pushed a fix a few weeks ago, the current build should be release-ready.

**Comment by modmuss50** [comment]
Ah awesome, thanks. I’ll push that as soon as I’m at a PC.

**Comment by gigabit101** [comment]
Its on curse waiting for approval

**Comment by gigabit101** [comment]
It is now live
