### ISSUE TITLE
reborn storage 3.0.6 causes crashes when starting autocrafting task

### ISSUE THREAD

**Issue by changhe3** [TechReborn/RebornStorage#99]
I created this crash twice. In both time I started autocrafting and the client crashed. For both time, reloading the saves causes another crash during loading. After I updated to 3.1.0, the crashed save can be loaded again.

My minecraft version is 1.1.12 and my forge version is 14.23.3.2702, here are the crash log for both times.
https://pastebin.com/k33rZe9R
https://pastebin.com/Fxt0VtyD

Since the crash is already resolved, I know you guys may not look into this but I'll just post it here in case you want to.

**Comment by modmuss50** [comment]
Make sure you have the latest version of refined storage
